import 'package:flutter/material.dart';

/// Small, dependency-free localization system covering the whole app.
///
/// Every user-facing string lives here in both English and Persian, so
/// switching to Persian translates the entire interface rather than only
/// flipping the layout direction. Keys are stable snake_case; a missing
/// key falls back to the English string, and then to the key itself, so
/// a translation gap can never render a blank label.
class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const supportedLocales = [Locale('en'), Locale('fa')];

  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'app_title': 'Poker Ledger',
      'tagline': 'Track Every Chip. Trust Every Session.',
      'new_session': 'New Session',
      'sessions': 'Sessions',
      'active_sessions': 'Active Sessions',
      'past_sessions': 'Past Sessions',
      'dashboard': 'Dashboard',
      'players': 'Players',
      'table': 'Table',
      'tables': 'Tables',
      'actions': 'Actions',
      'timeline': 'Timeline',
      'history': 'History',
      'reports': 'Reports',
      'settings': 'Settings',
      'search': 'Search',
      'search_sessions': 'Search sessions',
      'search_players': 'Search players',
      'no_sessions_yet': 'No sessions yet',
      'no_sessions_hint': 'Tap “New Session” to set up tonight\'s game — blinds, house rules and your five quick-rake buttons.',
      'active': 'Active',
      'ended': 'Ended',
      'on_break': 'On Break',
      'live': 'Live',
      'rake': 'Rake',
      'seated': 'seated',
      'session_name': 'Session Name',
      'location': 'Location',
      'date_time': 'Date & Time',
      'small_blind': 'Small Blind',
      'big_blind': 'Big Blind',
      'rake_percent': 'Rake %',
      'table_number': 'Table Number',
      'host_name_optional': 'Host Name (optional)',
      'currency': 'Currency',
      'toman': 'Toman',
      'english': 'English',
      'persian': 'Persian',
      'house_rules': 'House Rules',
      'house_rules_optional': 'House Rules (optional)',
      'rake_mode': 'Rake Mode',
      'fixed': 'Fixed',
      'tiered': 'Tiered',
      'create_session': 'Create Session',
      'total_buy_in': 'Total Buy-in',
      'total_rebuy': 'Total Rebuy',
      'total_cash_out': 'Total Cash-out',
      'rake_collected': 'Rake Collected',
      'host_profit': 'Host Profit',
      'money_in': 'Money In',
      'money_out': 'Money Out',
      'current_pot': 'Current Pot',
      'buy_in': 'Buy-in',
      'rebuy': 'Rebuy',
      'cash_out': 'Cash-out',
      'cash_drop': 'Cash Drop',
      'collect_rake': 'Collect Rake',
      'add_player': 'Add Player',
      'edit_player': 'Edit Player',
      'player_name': 'Player Name',
      'name': 'Name',
      'seat': 'Seat',
      'seats': 'Seats',
      'seat_number': 'Seat Number',
      'amount': 'Amount',
      'note': 'Note',
      'note_optional': 'Note (optional)',
      'initial_buy_in': 'Initial Buy-in',
      'skip_for_now': '0 to skip for now',
      'sign_here': 'Host: sign here to confirm',
      'clear': 'Clear',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'add': 'Add',
      'edit': 'Edit',
      'remove': 'Remove',
      'close': 'Close',
      'rename': 'Rename',
      'restore': 'Restore',
      'session_balanced': 'Session Balanced',
      'discrepancy_found': 'Discrepancy Found',
      'end_session': 'End Session',
      'export_pdf': 'Export PDF',
      'export_csv': 'Export CSV',
      'undo': 'Undo',
      'redo': 'Redo',
      'break_': 'Break',
      'resume': 'Resume',
      'favorites': 'Favorites',
      'vip': 'VIP',
      'regular': 'Regular',
      'problem_player': 'Problem Player',
      'tilt': 'Tilt',
      // --- Final localization sweep ---
      'free': 'free',
      'full': 'Full',
      'delete': 'Delete',
      'signature': 'Signature',
      'undone': 'Undone',
      'no_money': 'No money',
      'clear_slot': 'Clear slot',
      'level_label': 'Level',
      'cash_dropped_so_far': 'Cash dropped to safe so far',
      'cash_drop_to_safe': 'Cash Drop to Safe',
      'end_session_confirm_msg': 'This closes the session for further transactions. Continue?',
      'void_transaction': 'Void Transaction',
      'void_tx_message': 'This removes it from all balance totals but keeps it in the audit log as voided. You can restore it later. Continue?',
      'delete_transaction': 'Delete Transaction',
      'delete_tx_message': 'This PERMANENTLY removes this record. This cannot be undone, not even as a voided entry. Continue?',
      'rebuy_not_eligible_note': 'This player is not eligible for another rebuy at this level under the current house rules.',
      'money_in_buyin_rebuy': 'Money In (Buy-in + Rebuy)',
      'money_out_cashout_rake': 'Money Out (Cash-out + Rake + Dealer Tips)',
      'money_out_cashout_rake_tips': 'Money Out (Cash-out + Rake + Dealer Tips)',
      'cash_drops': 'Cash Drops',
      'export_failed': 'Export failed',
      'backup_failed': 'Backup failed',
      'restore_failed': 'Restore failed',
      'money_moving_with': 'Money moving with',
      'move_player_title': 'Move',
      'transfer_amount_label': 'Amount taking from this table',
      'transfer_amount_helper': 'Count the chips the player is carrying.',
      'transfer_table_note': 'This amount leaves the first table and arrives at the second. The session total is unchanged — the money has only changed table.',
      'move_player_note': 'You will be asked how much money they carry across. Their existing buy-ins, rebuys and cash-outs are never rewritten.',
      // Month names (Reports)
      'lifetime_label': 'Lifetime',
      'month_1': 'January',
      'month_2': 'February',
      'month_3': 'March',
      'month_4': 'April',
      'month_5': 'May',
      'month_6': 'June',
      'month_7': 'July',
      'month_8': 'August',
      'month_9': 'September',
      'month_10': 'October',
      'month_11': 'November',
      'month_12': 'December',
      // Chip sound samples (Settings)
      'sound_chip_1_title': 'Single Chip',
      'sound_chip_1_desc': 'One clean chip set down',
      'sound_chip_2_title': 'Chip Drop',
      'sound_chip_2_desc': 'A handful of chips dropped',
      'sound_chip_3_title': 'Chip Drop 2',
      'sound_chip_3_desc': 'A crisper handful, brighter tail',
      'sound_chip_4_title': 'Chip Cascade',
      'sound_chip_4_desc': 'A shorter pour, chips settling',
      'sound_chip_5_title': 'Chip Pour',
      'sound_chip_5_desc': 'A long cascade onto the felt',
      'sound_chip_6_title': 'Chip Pour 2',
      'sound_chip_6_desc': 'The fullest pour, longest tail',
      // --- Player classification & access status ---
      'tag_short_vip': 'VIP',
      'tag_short_regular': 'REG',
      'tag_short_problem': 'RISK',
      'tag_short_tilt': 'TILT',
      'player_type': 'Player Type',
      'change_player_type': 'Change Player Type',
      'manage_player': 'Manage player',
      'player_type_classification_note': 'classification only. Sessions, transactions and lifetime figures are never changed here.',
      'blacklist': 'Blacklist',
      'unblacklist': 'Unblacklist',
      'blacklisted': 'Blacklisted',
      'blacklisted_caps': 'BLACKLISTED',
      'blacklisted_player': 'Blacklisted Player',
      'blacklist_player_q': 'Blacklist player?',
      'blacklist_warning_body': 'will be flagged, and you will be warned before seating them in any future session or table.',
      'blacklist_warning_history': 'Their history, statistics and past sessions are not changed.',
      'is_currently_blacklisted': 'is currently on the blacklist.',
      'blacklist_seat_anyway': 'You can still seat them if you choose to.',
      'continue_action': 'Continue',
      'filter_all': 'All',
      'sort_recent': 'Recent',
      'sort_name': 'Name',
      'sort_sessions': 'Sessions',
      'sort_profit': 'Profit',
      // --- Dealer tips ---
      'dealer_tips': 'Dealer Tips',
      'total_dealer_tips': 'Total Dealer Tips',
      // --- Table-to-table transfer legs ---
      'transfer_out': 'Transfer Out',
      'transfer_in': 'Transfer In',
      'chips_to_player': 'Chips to',
      'chips_from_player': 'Chips from',
      // --- Timeline type summary ---
      'total_prefix': 'Total',
      // --- Home ---
      'total_rake_label': 'Total Rake',
      'signature_multi_stroke_hint': 'Sign using as many strokes as you need — lifting the pen will not end it. Press Confirm when finished.',
      'confirm_signature': 'Confirm Signature',
      'redraw': 'Redraw',
      'sample_signature': 'Sample signature',
      'verify_signature': 'Verify Signature',
      'sample_on_file': 'Sample on file',
      'transaction_signature': 'Signature on this transaction',
      'no_sample_signature': 'No sample signature was captured for this player.',
      'zoom': 'Zoom',
      'reset_zoom': 'Reset zoom',
      'pinch_to_zoom': 'Pinch or double-tap to zoom',
      'transaction_type': 'Transaction type',
      'date': 'Date',
      'saved': 'Saved',
      'host_signature': 'Host Signature',
      'signature_unavailable': 'Signature could not be displayed',
      'player_sample_signature': 'Player sample signature',
      'sample_signature_hint': 'Ask the player to sign once here. Kept on file purely so you can compare it against a disputed transaction later.',
      'recapture': 'Recapture',
      'private_tags': 'Private tags (banker only — never shown to the player)',
      'choose_seat_first': 'Choose a seat first.',
      'no_players_yet': 'No players yet.',
      'choose_player': 'Choose a player',
      'quick_actions': 'Quick Actions',
      'recent_activity': 'Recent Activity',
      'no_transactions_yet': 'No transactions yet.',
      'no_transactions_match': 'No transactions match.',
      'add_player_first': 'Add a player first to record buy-ins, rebuys, or cash-outs.',
      'one_tap': 'One tap:',
      'or_custom_amount': 'Or custom amount:',
      'pot_size': 'Pot Size',
      'rake_amount': 'Rake Amount',
      'confirm_custom_amount': 'Confirm Custom Amount',
      'quick_rake_buttons': 'Quick Rake Buttons',
      'enter_valid_amount': 'Enter a valid amount.',
      'signature_required': 'A host signature is required to confirm.',
      'unusually_large': 'Unusually Large Amount',
      'let_me_fix_it': 'Let Me Fix It',
      'its_correct': 'It\'s Correct',
      'zero_cashout_valid': '0 is valid — use it when a player busts out with no chips left.',
      'house_rule_notice': 'House Rule Notice',
      'proceed_anyway': 'Proceed Anyway',
      'view_rule': 'View Rule',
      'full_details': 'Full Details',
      'player_history': 'Player history across sessions',
      'lifetime': 'LIFETIME',
      'lifetime_pl': 'LIFETIME PROFIT / LOSS',
      'no_player_sessions': 'No sessions on record for this player yet.',
      'recent_sessions': 'RECENT SESSIONS',
      'sessions_played': 'sessions played',
      'in_play': 'In play',
      'settled': 'Settled',
      'playing': 'Playing',
      'move_to_table': 'Move to another table',
      'add_table': 'Add Table',
      'rename_table': 'Rename Table',
      'table_name': 'Table name',
      'table_size': 'Table size',
      'move_dealer': 'Move Dealer Button',
      'tap_seat_hint': 'Tap an empty seat to add a player · tap an occupied seat for actions',
      'more': 'More',
      'undo_last': 'Undo Last Transaction',
      'language': 'Language',
      'default_currency': 'Default Currency',
      'table_sounds': 'Table Sounds',
      'chip_sound': 'Poker chip sound',
      'preview_chip_sound': 'Preview chip sound',
      'chip_sound_desc': 'Plays the chip sound when you record a buy-in, rebuy, cash-out, rake or seat a player.',
      'privacy': 'Privacy',
      'privacy_mode': 'Privacy Mode',
      'privacy_desc': 'Hides every money amount on screen so nobody reading over your shoulder can see the numbers. Totals, the balance check and exported reports are unaffected.',
      'show_amounts': 'Show amounts',
      'hide_amounts': 'Hide amounts (privacy mode)',
      'set_pin': 'Set App PIN',
      'change_pin': 'Change App PIN',
      'pin_protect': 'Protects the app when it is opened',
      'enter_pin': 'Enter PIN',
      'enter_pin_confirm': 'Enter PIN to confirm',
      'unlock': 'Unlock',
      'pin_digits': '4–6 digit PIN',
      'backup_all': 'Backup All Data',
      'backup_desc': 'Exports every session, player, transaction, table and setting to a JSON file',
      'restore_backup': 'Restore From Backup',
      'restore_desc': 'Pick a previously exported JSON file to merge back in',
      'backup_created': 'Backup created and ready to share/save.',
      'session_report': 'Session Report',
      'possible_causes': 'Possible causes:',
      'all_reconcile': 'All buy-ins, rebuys, cash-outs and rake reconcile perfectly.',
      'session_ended_readonly': 'Session Ended — read only',
      'confirm_close_session': 'Confirm & Close Session',
      'go_back_fix': 'Go Back & Fix',
      'next_level': 'Next Level',
      'view_full_timeline': 'View Full Timeline →',
      'show_voided': 'Show voided',
      'voided': 'VOIDED',
      'edited': 'EDITED',
      'delete_permanently': 'Delete permanently',
      'transaction_updated': 'Transaction updated.',
      'filter_by_player': 'Filter by player',
      'all_players': 'All players',
      'session_timer': 'Session Timer',
      'session_duration': 'Session Duration',
      'time_remaining': 'Time Remaining',
      'minutes': 'minutes',
      'no_limit': 'No limit',
      'ten_min_remaining': '10 minutes remaining',
      'session_finished': 'Session finished',
      'start_timer': 'Start Timer',
      'stop_timer': 'Stop Timer',
      'complete_ledger': 'Complete Ledger',
      'every_action': 'Every action for this player, in order',
      'tournament': 'Tournament',
      'cash_game': 'Cash Game',
      'game_mode': 'Game Mode',
      'tournament_setup': 'Tournament Setup',
      'tournament_setup_hint': 'Entry cost, house fee and the opening blind structure. Every level can be customised once the tournament starts.',
      'tournament_buy_in': 'Tournament Buy-in',
      'house_fee_per_entry': 'House Fee per Entry',
      'rebuy_cost': 'Rebuy Cost',
      'blank_for_none': 'leave blank for none',
      'starting_stack': 'Starting Stack',
      'level_length': 'Level (min)',
      'blind_structure': 'Blind Structure',
      'blind_structure_hint': 'Drag to reorder, tap to edit. Add as many levels and breaks as you need.',
      'structure_saved': 'Blind structure saved.',
      'add_level': 'Add Level',
      'add_break': 'Add Break',
      'level': 'Level',
      'is_break': 'This is a break',
      'ante': 'Ante',
      'duration_minutes': 'Duration (minutes)',
      'prize_pool': 'Prize Pool',
      'payouts': 'Payouts',
      'entries': 'Entries',
      'house_fee': 'House Fee',
      'unpaid': 'Unpaid',
      'rankings': 'Rankings',
      'still_in': 'still in',
      'eliminated': 'Eliminated',
      'eliminate': 'Eliminate',
      'eliminate_hint': 'The finishing position is worked out from how many players are still in, so eliminate players in the order they bust.',
      'finishes_in_the_money': 'Finishes in the money:',
      'finishes_outside_money': 'Finishes outside the money.',
      'next': 'Next',
      'previous_level': 'Previous level',
      'reset': 'Reset',
      'five_min_remaining': '5 minutes remaining',
      'one_min_remaining': '1 minute remaining',
      'level_finished': 'Level finished — blinds up',
      'total': 'Total',
      'add_place': 'Add Place',
      'suggest': 'Suggest',
      'payouts_must_total_100': 'Payout percentages must add up to exactly 100%.',
      'session_summary': 'Session Summary',
      'player_performance': 'Player Performance',
      'lifetime_statistics': 'Lifetime Statistics',
      'monthly_statistics': 'Monthly Statistics',
      'banker_profit': 'Banker Profit',
      'export': 'Export',
      'share': 'Share',
      'generated': 'Generated',
      'no_data_yet': 'No data yet.',
      'profit_loss': 'Profit / Loss',
      'net': 'Net',
      'months': 'months',
      'average': 'average',
      'more_in_export': 'more in the export',
      'tournament_report': 'Tournament Report',
      'app_start_failed': 'Poker Ledger Couldn\'t Start',
      'verified_session_level': 'Verified at the session level only — Total Buy-ins + Rebuys vs. Total Cash-outs + Rake.',
      'timer_hint': 'You will be told when 10 minutes are left, and when the time is up. The session is never ended automatically.',
      'tables_upper': 'TABLES',
      'per_table_note': 'Per-table figures are money still in play at each table. The balance check above covers the whole session.',
      'zero_valid_bustout': '0 is valid for a bust-out cash-out.',
      'resign_to_confirm': 'Re-sign to confirm this edit:',
      'signature_required_edit': 'A signature is required to confirm this edit.',
      'search_by_player_or_note': 'Search by player or note',
      'house_rules_updated': 'House rules updated.',
      'open_session_for_rules': 'Open an active session to view or edit its house rules.',
      'enforce_rebuy_levels': 'Enforce rebuy levels',
      'rebuy_unlock_note': 'One extra rebuy unlocks every two levels.',
      'five_slots_note': 'Five slots you define yourself — one-tap amounts in Collect Rake.',
      'save_house_rules': 'Save House Rules',
      'under': 'Under',
      'tier_default_note': 'Starts with the house-default tier table; fine-tune exact thresholds and amounts from House Rules once the session is open.',
      'define_five_note': 'Define your own five one-tap rake amounts for tonight. You can change them any time from House Rules once the game is running.',
      'host_signature_required_tx': 'A host signature is required to confirm this transaction.',
      'sample_signature_on_file': 'Sample signature on file',
      'actual_payout_note': 'Enter the actual payout — this is not limited by what the player bought in for.',
      'mixed_currency_note': 'This player has sessions in more than one currency, so lifetime totals are not shown — adding Toman to dollars would be meaningless. Per-session results below are still exact.',
      'ask_player_sign_note': 'Ask the player to sign once here. Kept on file purely so you can compare it against a disputed transaction later.',
      'activation_title': 'Activate Poker Ledger',
      'activation_subtitle': 'This copy needs a license key before it can be used.',
      'license_key': 'License Key',
      'license_key_hint': 'Paste the license key you received',
      'activate': 'Activate',
      'activation_success': 'Activated. Thank you.',
      'activation_how_title': 'How to get a license',
      'activation_how_body': 'Send the Device ID below to the owner of Poker Ledger. They will issue a license key for this device.',
      'device_id': 'Device ID',
      'platform': 'Platform',
      'customer_id': 'Customer ID',
      'device_id_copied': 'Device ID copied',
      'copy': 'Copy',
      'app_lock': 'App Lock',
      'app_lock_title': 'Poker Ledger is locked',
      'app_lock_reason': 'Confirm it is you to open your ledger.',
      'app_lock_unlock': 'Unlock',
      'app_lock_enable': 'Enable App Lock',
      'app_lock_enabled': 'App Lock enabled',
      'app_lock_disabled': 'App Lock disabled',
      'app_lock_desc': 'Requires your fingerprint, face or device PIN each time you open Poker Ledger — the same protection a banking app uses.',
      'app_lock_status': 'Status',
      'auto_lock': 'Auto-lock',
      'auto_lock_desc': 'How long Poker Ledger may stay in the background before it locks again.',
      'lock_immediately': 'Immediately',
      'lock_after_1': 'After 1 minute',
      'lock_after_5': 'After 5 minutes',
      'lock_after_15': 'After 15 minutes',
      'app_lock_failed': 'Not recognised. Try again.',
      'app_lock_cancelled': 'Authentication cancelled. Poker Ledger stays locked.',
      'app_lock_not_recognized': 'Not recognised',
      'app_lock_required': 'Authentication required',
      'app_lock_not_enrolled': 'No fingerprint, face or screen lock is set up on this device. Add one in your device settings to use App Lock.',
      'app_lock_unavailable': 'This device cannot use App Lock.',
      'app_lock_locked_out': 'Too many attempts. Your device has blocked authentication for a while — use your device PIN or wait and try again.',
      'app_lock_privacy_note': 'Your device checks your fingerprint, face or PIN. Poker Ledger never sees or stores any of it.',
      'app_lock_biometrics_available': 'Biometrics available on this device',
      'app_lock_credential_only': 'Device PIN, pattern or password only',
      'app_lock_unsupported_note': 'This device has no screen lock or biometric set up, so App Lock cannot be enabled.',
      'chip_bank': 'Chip Bank',
      'chip_bank_desc': 'Track the physical poker chips you own — how many of each denomination, and what the whole case is worth.',
      'chip_inventory': 'Chip Inventory',
      'add_chip_type': 'Add Chip Type',
      'edit_chip_type': 'Edit Chip Type',
      'chip_name': 'Chip name',
      'chip_name_optional': 'Chip name (optional)',
      'chip_color': 'Chip colour',
      'chip_color_optional': 'Chip colour (optional)',
      'chip_value': 'Chip value',
      'chip_value_required': 'Value per chip (required)',
      'chip_quantity': 'Quantity',
      'chip_quantity_required': 'Quantity owned (required)',
      'chip_note_optional': 'Note (optional)',
      'no_color': 'No colour',
      'total_chip_bank_value': 'Total Chip Bank Value',
      'total_chips': 'Total chips',
      'chip_types': 'Chip types',
      'value_each': 'each',
      'no_chips_yet': 'No chip types added yet.',
      'no_chips_hint': 'Add your first denomination to start tracking your chip case. Only value and quantity are required — name and colour are optional.',
      'chip_added': 'Chip type added',
      'chip_updated': 'Chip type updated',
      'chip_removed': 'Chip type removed',
      'remove_chip_confirm': 'Remove this chip type from your inventory? This does not affect any session, player or transaction.',
      'chip_value_invalid': 'Enter a chip value greater than zero.',
      'chip_quantity_invalid': 'Enter a quantity of zero or more.',
      'last_updated': 'Last updated',
      'chip_bank_ledger_note': 'This is a physical inventory only. It never affects buy-ins, player balances or the settlement of any session.',
      'update_inventory': 'Update inventory',
      'unnamed_chip': 'Unnamed chip',
      'chip_tracking': 'Chip Tracking',
      'distribute_chips': 'Distribute chips',
      'chips_given': 'Chips given',
      'chip_distribution': 'Chip distribution',
      'chip_distribution_optional': 'Optional — record which physical chips you handed over.',
      'suggest_chips': 'Suggest',
      'clear_chips': 'Clear',
      'chip_total': 'Chip total',
      'target_amount': 'Transaction amount',
      'chip_mismatch_title': 'Chip value does not match',
      'chip_mismatch_body': 'The chips you selected are worth a different amount than this transaction. This is allowed — the money is recorded either way — but please confirm it is intentional.',
      'chip_mismatch_short': 'Chips do not match the amount',
      'record_anyway': 'Record anyway',
      'chips_match': 'Chips match the amount',
      'bank_cannot_cover': 'The bank does not physically hold this many chips.',
      'skip_chips': 'Skip chip tracking',
      'chip_audit': 'Chip Audit',
      'chip_reconciliation': 'Chip Reconciliation',
      'total_inventory': 'Total inventory',
      'in_bank': 'In bank',
      'on_tables': 'On tables',
      'with_players': 'With players',
      'removed_chips': 'Removed',
      'accounted_for': 'Accounted for',
      'expected_in_bank': 'Expected in bank',
      'counted_in_bank': 'Counted',
      'physical_count': 'Physical count',
      'physical_count_hint': 'Count the case and enter what you actually have. Leave blank to skip a denomination.',
      'chips_balanced': 'All counted chips reconcile.',
      'chips_discrepancy': 'Chip discrepancy',
      'chips_missing': 'unaccounted for',
      'chips_extra': 'more than expected',
      'possible_locations': 'Check these first',
      'not_verified_note': 'No physical count entered yet, so nothing has been verified. Enter a count to reconcile.',
      'verify_count': 'Enter physical count',
      'chip_movements': 'Chip Movements',
      'movement_history': 'Movement history',
      'no_movements_yet': 'No chip movements recorded yet.',
      'chips_held': 'Physical chips held',
      'total_chip_value': 'Total chip value',
      'no_chips_held': 'No physical chips recorded for this player.',
      'chips_on_table': 'Chips on this table',
      'all_tables_chips': 'Chips across all tables',
      'move_chips': 'Move chips',
      'from_location': 'From',
      'to_location': 'To',
      'location_bank': 'Bank',
      'location_table': 'Table',
      'location_player': 'Player',
      'location_removed': 'Removed from play',
      'reason_buy_in': 'Buy-in',
      'reason_rebuy': 'Rebuy',
      'reason_add_on': 'Add-on',
      'reason_cash_out': 'Cash-out',
      'reason_table_float': 'Table float',
      'reason_rake': 'Rake',
      'reason_adjustment': 'Adjustment',
      'reason_transfer': 'Transfer',
      'chip_tracking_note': 'Physical chip tracking only. It never changes buy-ins, balances, rake or settlement.',
      'players_holding_chips_note': 'Chips held by players are not missing — winning and losing moves chips around the table all night. They are simply counted where they are.',
      'chips_returned': 'Returned to bank',
      'return_chips': 'Return chips to bank',
      'movement_recorded': 'Chip movement recorded',
      'set_duration': 'Timer duration',
      'table_duration_desc': 'This table only. Other tables keep their own timers.',
      'no_timer': 'No timer',
      'custom_minutes': 'Custom (minutes)',
      'timer_finished': 'FINISHED',
      'minute_timer_finished': 'minute timer finished',
      'view_table': 'View table',
      'total_rake': 'Total Rake',
      'bank': 'Bank',
      'bank_only': 'Bank inventory only',
      'cancel_count': 'Cancel count',
      'chip_accounting': 'Chip Accounting',
      'chip_bank_critical_alert': 'Chip Bank critically low — 30% or less of the starting inventory remains.',
      'chip_bank_low_alert': 'Chip Bank is running low — half the starting inventory has been issued.',
      'chip_composition_updated': 'Chip composition updated',
      'chip_exchange': 'Chip Exchange',
      'chip_exchange_desc': 'Swap denominations with the Bank at equal value. No money changes hands.',
      'chips_balanced_body': 'The chips you counted match what the movement log expects. Every chip is accounted for.',
      'chips_given_to_bank': 'Chips given to the Bank',
      'chips_held_by_players': 'Chips held by players',
      'chips_missing_body': 'Fewer chips were counted than the records expect. A movement was probably never written down. This is reported, not corrected.',
      'chips_on_tables': 'Chips on tables',
      'chips_received_from_bank': 'Chips received from the Bank',
      'chips_surplus': 'More chips than expected',
      'chips_surplus_body': 'More chips were counted than the records expect. Check for a movement recorded twice, or chips returned without being logged.',
      'chips_to_transfer': 'Chips to transfer',
      'choose_both_players': 'Choose both players.',
      'choose_player_first': 'Choose a player first.',
      'choose_source_player_first': 'Choose the source player first.',
      'confirm_exchange': 'Confirm exchange',
      'confirm_transfer': 'Confirm transfer',
      'counted': 'Counted',
      'current_bank_chip_value': 'Current Bank chip value',
      'difference': 'Difference',
      'edit_chip_composition': 'Edit chip composition',
      'edit_chip_composition_note': 'Corrects which physical chips were handed over. The transaction amount is not changed.',
      'edit_keeps_audit_trail': 'The original entry is kept. A reversal and the correction are added, so the full history stays visible.',
      'enter_count': 'Enter count',
      'exchange_balanced': 'Both sides balance',
      'exchange_empty': 'Select the chips on both sides.',
      'exchange_must_balance': 'Both sides must be exactly equal in value.',
      'exchange_no_money_note': 'Records physical chips only. No transaction is created and settlement is unaffected.',
      'exchange_recorded': 'Exchange recorded',
      'expected': 'Expected',
      'expected_total_chips': 'Expected total chips',
      'final_discrepancy': 'Final discrepancy',
      'from_player': 'From player',
      'given': 'Given',
      'included_in_bank_total': 'Already included in the Bank total above',
      'new_chip_total': 'New chip total',
      'no_chips_recorded': 'No chips were recorded for this transaction.',
      'not_entered': 'Not entered',
      'not_yet_verified': 'Not yet verified',
      'not_yet_verified_body': 'Every figure below is derived from the movement log, so it balances by construction. Count the case and enter the result to check it against reality.',
      'of_starting_inventory_remains': 'of the starting inventory remains',
      'originally_recorded': 'Originally recorded',
      'player_chip_transfer': 'Player-to-Player Transfer',
      'player_chip_transfer_desc': 'Move physical chips between two players. The Bank and settlement are untouched.',
      'player_holds': 'Player holds',
      'player_lacks_chips': 'That player does not hold enough of those chips.',
      'prefill_expected': 'Prefill expected',
      'prefill_expected_hint': 'Fills each field with the expected count so you only change what differs. Adjust every line you actually counted.',
      'rake_returned_to_bank': 'Rake returned to Bank',
      'received': 'Received',
      'reconcile_chips_before_closing': 'Reconcile chips before closing',
      'reconciliation_never_adjusts': 'This report never creates or removes chips. A real discrepancy is always shown, never silently corrected.',
      'removed_lost_damaged': 'Removed / lost / damaged',
      'save_composition': 'Save composition',
      'select_chips_to_transfer': 'Select the chips to transfer.',
      'select_player': 'Select player',
      'session_chip_reconciliation': 'Session Chip Reconciliation',
      'starting_bank_chip_value': 'Starting Bank chip value',
      'to_player': 'To player',
      'transaction_amount': 'Transaction amount',
      'transfer_no_money_note': 'Records physical chips only. Bank inventory, balances and settlement are all unaffected.',
      'transfer_recorded': 'Transfer recorded',
      'transfer_value': 'Transfer value',
      'unknown_chip': 'Unknown chip',
      'unverified': 'Unverified',
      'view': 'View',
      'was': 'Was',
      'license': 'License',
      'license_status': 'License Status',
      'license_id': 'License ID',
      'licensed_to': 'Licensed To',
      'license_type': 'License Type',
      'activation_date': 'Activation Date',
      'expiry_date': 'Expiry Date',
      'never_expires': 'Never expires',
      'device_limit': 'Device Limit',
      'device_info': 'Device Information',
      'status_active': 'Active',
      'status_not_activated': 'Not activated',
      'status_expired': 'Expired',
      'status_invalid': 'Invalid',
      'deactivate_device': 'Deactivate this device',
      'deactivate_desc': 'Releases this device so the license can be used on another phone. Your sessions, players and transactions are NOT deleted.',
      'deactivate_confirm': 'Deactivate this device? You will need the license key again to keep using the app. No ledger data is deleted.',
      'deactivate_done': 'Device deactivated',
      'license_scope': 'Scope',
      'owner_master_license': 'Owner master license',
      'multi_device_note': 'This license may be activated on more than one of your own devices. Activating another device does not deactivate this one.',
      'license_type_club': 'Club',
      'license_type_full': 'Full',
      'license_type_standard': 'Standard',
      'license_type_trial': 'Trial',
      'license_type_owner': 'Owner',
      'days_remaining': 'days remaining',
      'err_license_empty': 'Enter a license key.',
      'err_license_malformed': "This doesn't look like a Poker Ledger license key. Check that you copied all of it.",
      'err_license_signature': 'This license key is not valid. It was not issued by Poker Ledger, or it has been altered.',
      'err_license_expired': 'This license has expired. Contact the owner for a renewal.',
      'err_license_device': 'This license is registered to a different device. Ask the owner for a key for this device.',
      'err_license_limit': 'This license has reached its device limit.',
      'err_license_future': 'This license needs a newer version of the app.',
      'err_license_tampered': 'The saved activation is no longer valid. Please activate again.',
      'license_data_safe_note': 'Activation only unlocks the app. It never touches your sessions, players or transactions.',
      'license_offline_note': 'Works fully offline once activated. No internet connection is required.',
      'reactivate': 'Re-activate',
      'restore_backup_title': 'Restore Backup',
      'restore_merge_note': 'This will merge the selected backup into your current data. Sessions, players and transactions with matching IDs will be overwritten; everything else is kept. Identities that look like they might be the same person are NOT merged — you will be asked. This cannot be undone.',
      'chip_sound_desc_long': 'Plays the chip sound when you record a buy-in, rebuy, cash-out, rake or seat a player — so you can hear the action registered without looking at the screen.',
      'privacy_desc_long': 'Hides every money amount on screen so nobody reading over your shoulder can see the numbers. Totals, the balance check and exported reports are unaffected — it only masks the display. Also on the eye icon in any live session.',
      'backup_exports_note': 'Exports every session, player, identity, transaction, table, setting and player-registry entry to a JSON file',
      'no_quick_rake_set': 'No quick rake buttons configured — set your five amounts in House Rules.',
      'heads_up_no_cashout': 'Heads up: no cash-out is recorded for',
      'no_cashout_double_check': 'The totals still balance, but double-check these players were actually settled.',
      'signature_score_disclaimer': 'This score is an aid, not a verdict. Nothing is blocked or approved automatically — the decision is yours.',
      'edit_player_tooltip': 'Edit player',
      'leave_blank_hide': 'leave blank to hide this button',
      'five_buttons_note': 'These five buttons appear at the top of Collect Rake for one-tap entry. A custom amount is always available underneath them.',
      'no_quick_rake_configured': 'No quick rake buttons configured — Collect Rake will ask for a custom amount only.',
      'comparison_note': 'Comparison is a human judgement — Poker Ledger shows both marks and never scores them. Treat a mismatch as a reason to ask the player, not as proof on its own.',
      'tables_seating_note': 'Tables organise seating only. All buy-ins, rebuys, rake and the end-of-night balance stay session-wide — you settle one bank, not one per table.',
      'eg_table_2': 'e.g. Table 2',
      'only_one_table_note': 'There is only one table in this session. Add another from the More menu to move players between tables.',
      'view_signature': 'view signature',
      'all_tables': 'All Tables',
      'paused': 'Paused',
      'closed': 'Closed',
      'pause': 'Pause',
      'reopen': 'Reopen',
      'close_table': 'Close Table',
      'close_table_confirm': 'Close',
      'close_table_note': 'The session stays open. Other tables keep running, and you can reopen this table at any time.',
      'table_closed_hint': 'This table is closed. Reopen it to seat players or record money.',
      'quick_rake': 'Quick Rake',
      'rake_from_this_player': 'Rake from this player\'s pot',
      'rake_from_player': 'Rake from',
      'rake_general_note': 'General session rake — not tied to any player.',
      'rake_from_their_pots': 'Rake from their pots',
      'rake_not_in_pl': 'Rake is house income and is never counted against this player\'s profit or loss.',
      'across_all_sessions': 'Across all sessions',
      'win_rate': 'Win Rate',
      'average_buy_in': 'Average Buy-in',
      'start_timer_table': 'Start table timer',
      'chip_sound_pick_hint': 'All chip actions use the sound you pick here. Tap any option to hear it.',
      // --- Player identity (Step 1 — no money) ---
      'identity_same_person_title': 'Same person?',
      'identity_same_person_body': 'Someone named {name} is already on file. Tap the matching person to link this seat — or say this is someone else. A name is not enough on its own.',
      'identity_different_person': 'Different person',
      'identity_confirm_hint': 'Linking is never automatic. If you are not sure, choose Different person — two people may share a name.',
      'identity_last_seen': 'Last seated',
      'identity_no_previous_seat': 'No previous seat linked',
      'identity_restore_conflict_title': 'Identity conflict',
      'identity_restore_conflict_same_id': 'This backup identity has the same id as one already on this device, but the names do not match. Overwriting would relabel that person. Choose which spelling to keep.',
      'identity_restore_conflict_same_name': 'This backup identity has the same name as someone already on this device, but a different id. They will not be merged. Import both if they are two people, or skip the incoming one.',
      'identity_keep_local': 'Keep mine',
      'identity_take_backup': 'Use backup',
      'identity_keep_both': 'Keep both',
      'identity_conflicts_resolved': 'Identity conflicts were resolved one by one.',
      'identity_conflicts_pending': 'Some identities were not imported because they conflict with people already on this device.',
      // --- Financial Ledger (Step 2 — read-only account) ---
      'player_account': 'Player Account',
      'view_financial_account': 'Financial account',
      'outstanding_balance': 'Outstanding Balance',
      'not_recorded': 'Not recorded',
      'not_recorded_hint': 'No real-money events have been recorded for this person in this currency. That is not the same as settled — it means the Financial Ledger has no history yet.',
      'not_recorded_no_identity': 'This seat is not linked to a permanent identity, so there is no financial account to show.',
      'financial_history': 'FINANCIAL HISTORY',
      'no_financial_events': 'No financial events yet.',
      'fin_cash_in_for_chips': 'Cash-in for chips',
      'fin_cash_out_for_chips': 'Cash-out for chips',
      'fin_credit_issued': 'Credit issued',
      'fin_credit_repaid': 'Credit repaid',
      'fin_cash_out_unbacked': 'Cash-out unbacked',
      'fin_front_money_in': 'Deposit in',
      'fin_front_money_out': 'Deposit out',
      'fin_deposit_in': 'Deposit in',
      'fin_deposit_out': 'Deposit out',
      'fin_adjustment': 'Adjustment',
      'fin_reversal_of': 'Reversal of',
      'payment_cash': 'Cash',
      'payment_bank_transfer': 'Bank transfer',
      'payment_other': 'Other',
      'player_owes_banker': 'Player owes the banker',
      'banker_holds_money': 'Banker is holding this player\'s money',
      'financial_settled': 'Settled — nothing outstanding',
      'backdated': 'BACKDATED',
      'reversed_event': 'REVERSAL',
      'audit_linked_tx': 'Linked chip transaction (audit only — not proof of payment)',
      'financial_account_chip_note': 'Real money between you and this person. Chip buy-ins, rebuys and cash-outs are a separate ledger and are never added in here.',
      // --- Step 3: cash-in / credit / marker capture ---
      'how_was_this_paid': 'How did they pay for these chips?',
      'funding_not_inferred': 'A chip buy-in is not proof of payment. Choose what actually happened, or skip to leave it Not recorded.',
      'funding_paid_cash': 'Paid cash',
      'funding_paid_cash_hint': 'They handed over this amount. Nobody owes anybody.',
      'funding_credit': 'Credit',
      'funding_credit_hint': 'Chips now, they pay later. Creates a debt.',
      'funding_marker': 'Marker',
      'funding_marker_hint': 'Same as credit, with their signature as evidence.',
      'funding_not_recorded': 'Skip — not recorded',
      'funding_not_recorded_hint': 'Do not write a financial event. This is not the same as settled.',
      'marker_sign_hint': 'Ask the player to sign this marker.',
      'confirm_marker': 'Confirm marker',
      'how_was_cashout_paid': 'How was this cash-out paid?',
      'cashout_funding_hint': 'Chips coming back is not proof you paid them cash.',
      'cashout_paid_cash': 'Paid cash',
      'cashout_paid_cash_hint': 'You handed them this amount for the chips they returned.',
      'cashout_unbacked': 'Unbacked',
      'cashout_unbacked_hint': 'You paid them cash they had not covered. They owe you.',
      'financial_record_failed': 'Chip movement was saved. The financial record failed',
      'record_credit_repaid': 'Record credit repayment',
      'credit_repaid_hint': 'They are paying down what they owe. This is not a chip buy-in.',
      // --- Step 4: Front Money ---
      'accept_front_money': 'Accept Deposit',
      'return_front_money': 'Return Deposit',
      'front_money_in_hint': 'They handed you cash as a deposit. This is not a chip buy-in and not a credit repayment.',
      'front_money_out_hint': 'You are returning their deposit. This is not a chip cash-out.',
      'front_money_held': 'Remaining Deposit',
      'accept_deposit': 'Accept Deposit',
      'return_deposit': 'Return Deposit',
      'use_deposit_for_chips': 'Use Deposit for Chips',
      'remaining_deposit': 'Remaining Deposit',
      'deposit_in_hint': 'They handed you cash as a deposit. It is not a chip buy-in, not credit, and not playing money until you convert it.',
      'deposit_out_hint': 'Return deposited cash. This is not a chip cash-out and does not affect Discount.',
      'deposit_use_chips_hint': 'Convert this much of their deposit into chips. The amount leaves Deposit and is recorded as cash-in for chips. A regular Buy-in is not inferred.',
      'deposit_need_session': 'Seat this person in a live session before converting deposit into chips.',
      'deposit_need_seat': 'This person is not seated in the session. Seat them before converting deposit into chips.',
      'deposit_sign_hint': 'Host: sign to confirm these chips come from their deposit.',
      // --- Step 5: Settlement / Reports ---
      'settle_poker_chips': 'POKER CHIP SETTLEMENT',
      'settle_financial_account': 'FINANCIAL ACCOUNT',
      'settle_deposit': 'DEPOSIT',
      'settle_buy_in': 'Buy-in',
      'settle_rebuy': 'Rebuy',
      'settle_cash_out': 'Cash-out',
      'settle_current_pot': 'Current pot / discrepancy',
      'settle_cashed_out': 'Cash-out recorded',
      'settle_not_cashed_out': 'No cash-out recorded',
      'settle_credit_issued': 'Credit issued',
      'settle_credit_repaid': 'Credit repaid',
      'settle_unbacked': 'Unbacked cash-out',
      'settle_cash_in_for_chips': 'Cash paid for chips',
      'settle_cash_out_for_chips': 'Cash received for returned chips',
      'settle_deposit_in': 'Deposit received',
      'settle_deposit_used': 'Deposit used for chips',
      'settle_deposit_returned': 'Deposit returned',
      'settle_deposit_remaining': 'Deposit remaining',
      'settle_warn_deposit': 'This session still has Deposit held. You can return it after the session closes.',
      'settle_warn_credit': 'This session still has outstanding credit. You can record repayment after the session closes.',
      'settle_warn_unbacked': 'This session still has an unbacked cash-out. You can correct it after the session closes.',
      'void_linked_title': 'Linked financial events',
      'void_linked_body': 'This chip transaction is connected to financial events. Voiding the chip row does not automatically reverse them. Choose what to do.',
      'void_chip_only': 'Void chip transaction only',
      'void_chip_and_reverse': 'Void chip + reverse linked financial events',
      'void_chip_only_warn': 'The chip row was voided. Linked financial events were left in place and may need a separate correction.',
      // --- Step 6: Loss rebate / Discount ---
      'rebate_title': 'LOSS REBATE',
      'rebate_enabled': 'Enable loss rebate',
      'rebate_min_loss': 'Minimum qualifying own-cash loss',
      'rebate_percent': 'Rebate percent',
      'rebate_hint': 'Cash game only. Based on cash paid for chips, not Buy-in rows, Credit, or Deposit.',
      'rebate_granted': 'Discount granted',
      'rebate_returned': 'Discount returned to house',
      'rebate_paid_out': 'Discount paid to player',
      'rebate_exposed': 'Discount still in play',
      'rebate_house_retained': 'House retained from own cash',
      'rebate_own_cash_in': 'Player own cash in',
      'rebate_own_cash_out': 'Recorded chip cash-out',
      'rebate_actual_paid': 'Cash actually paid to player',
      'rebate_eligible_loss': 'Eligible own-cash loss',
      'rebate_gross_loss': 'Gross own-cash loss',
      'review_discount': 'Review Discount',
      'confirm_rebate_grant': 'Confirm Discount grant',
      'rebate_as_chips': 'Grant as chips',
      'rebate_as_cash': 'Grant as cash',
      'rebate_as_chips_hint': 'Promotional chips. Not a Buy-in and not the player\'s own cash.',
      'rebate_as_cash_hint': 'Cash paid to the player. Not a chip Buy-in.',
      'rebate_not_eligible': 'No Discount to grant',
      'rebate_realize_title': 'Discount on this cash-out',
      'rebate_realize_body': 'The player still receives the cash-out amount. Unused Discount that was lost in play returns to the house. A larger cash-out only recovers the remaining grant — never a new percent.',
      'rebate_player_receives': 'Player receives',
      'rebate_returned_now': 'Returned to house now',
      'confirm_rebate_realize': 'Record Discount realisation',
      'reverse_rebate_grant': 'Reverse this Discount grant',
      'fin_rebate_granted': 'Discount granted',
      'fin_rebate_recovered': 'Discount returned to house',
      'reason_loss_rebate': 'Loss rebate',
      'settle_warn_rebate_chips': 'Discount chips were issued this session. They are not Money In. When cashed they can make poker chip books look short by that amount.',
      'rebate_form_chips': 'as chips',
      'rebate_form_cash': 'as cash',
    },
    'fa': {
      'app_title': 'دفتر پوکر',
      'tagline': 'هر ژتون را ثبت کن. به هر نشست اعتماد کن.',
      'new_session': 'نشست جدید',
      'sessions': 'نشست‌ها',
      'active_sessions': 'نشست‌های فعال',
      'past_sessions': 'نشست‌های گذشته',
      'dashboard': 'داشبورد',
      'players': 'بازیکنان',
      'table': 'میز',
      'tables': 'میزها',
      'actions': 'عملیات',
      'timeline': 'خط زمانی',
      'history': 'تاریخچه',
      'reports': 'گزارش‌ها',
      'settings': 'تنظیمات',
      'search': 'جستجو',
      'search_sessions': 'جستجوی نشست‌ها',
      'search_players': 'جستجوی بازیکنان',
      'no_sessions_yet': 'هنوز نشستی ثبت نشده',
      'no_sessions_hint': 'برای شروع بازی امشب روی «نشست جدید» بزنید — بلایندها، قوانین خانه و پنج دکمه راک سریع.',
      'active': 'فعال',
      'ended': 'پایان‌یافته',
      'on_break': 'در استراحت',
      'live': 'زنده',
      'rake': 'راک',
      'seated': 'نشسته',
      'session_name': 'نام نشست',
      'location': 'مکان',
      'date_time': 'تاریخ و زمان',
      'small_blind': 'بلایند کوچک',
      'big_blind': 'بلایند بزرگ',
      'rake_percent': 'درصد راک',
      'table_number': 'شماره میز',
      'host_name_optional': 'نام میزبان (اختیاری)',
      'currency': 'واحد پول',
      'toman': 'تومان',
      'english': 'انگلیسی',
      'persian': 'فارسی',
      'house_rules': 'قوانین خانه',
      'house_rules_optional': 'قوانین خانه (اختیاری)',
      'rake_mode': 'حالت راک',
      'fixed': 'ثابت',
      'tiered': 'پلکانی',
      'create_session': 'ایجاد نشست',
      'total_buy_in': 'مجموع خرید ورود',
      'total_rebuy': 'مجموع شارژ مجدد',
      'total_cash_out': 'مجموع تسویه',
      'rake_collected': 'راک جمع‌آوری‌شده',
      'host_profit': 'سود میزبان',
      'money_in': 'پول ورودی',
      'money_out': 'پول خروجی',
      'current_pot': 'پول روی میز',
      'buy_in': 'خرید ورود',
      'rebuy': 'شارژ مجدد',
      'cash_out': 'تسویه',
      'cash_drop': 'واریز به صندوق',
      'collect_rake': 'جمع‌آوری راک',
      'add_player': 'افزودن بازیکن',
      'edit_player': 'ویرایش بازیکن',
      'player_name': 'نام بازیکن',
      'name': 'نام',
      'seat': 'صندلی',
      'seats': 'صندلی‌ها',
      'seat_number': 'شماره صندلی',
      'amount': 'مبلغ',
      'note': 'یادداشت',
      'note_optional': 'یادداشت (اختیاری)',
      'initial_buy_in': 'خرید ورود اولیه',
      'skip_for_now': 'برای رد شدن ۰ بگذارید',
      'sign_here': 'میزبان: برای تایید امضا کنید',
      'clear': 'پاک کردن',
      'confirm': 'تایید',
      'cancel': 'انصراف',
      'save': 'ذخیره',
      'add': 'افزودن',
      'edit': 'ویرایش',
      'remove': 'حذف',
      'close': 'بستن',
      'rename': 'تغییر نام',
      'restore': 'بازیابی',
      'session_balanced': 'نشست متعادل است',
      'discrepancy_found': 'مغایرت پیدا شد',
      'end_session': 'پایان نشست',
      'export_pdf': 'خروجی PDF',
      'export_csv': 'خروجی CSV',
      'undo': 'واگرد',
      'redo': 'ازنو',
      'break_': 'استراحت',
      'resume': 'ادامه',
      'favorites': 'موردعلاقه‌ها',
      'vip': 'وی‌آی‌پی',
      'regular': 'عادی',
      'problem_player': 'بازیکن مشکل‌دار',
      'tilt': 'تیلت',
      // --- Final localization sweep ---
      'free': 'آزاد',
      'full': 'پر',
      'delete': 'حذف',
      'signature': 'امضا',
      'undone': 'برگردانده شد',
      'no_money': 'بدون پول',
      'clear_slot': 'پاک کردن خانه',
      'level_label': 'سطح',
      'cash_dropped_so_far': 'وجه منتقل‌شده به گاوصندوق تا این لحظه',
      'cash_drop_to_safe': 'انتقال وجه به گاوصندوق',
      'end_session_confirm_msg': 'با این کار جلسه برای ثبت تراکنش جدید بسته می‌شود. ادامه می‌دهید؟',
      'void_transaction': 'ابطال تراکنش',
      'void_tx_message': 'این مورد از همه‌ی جمع‌های مالی حذف می‌شود اما به‌عنوان باطل‌شده در سوابق باقی می‌ماند. بعداً می‌توانید آن را برگردانید. ادامه می‌دهید؟',
      'delete_transaction': 'حذف تراکنش',
      'delete_tx_message': 'این رکورد برای همیشه حذف می‌شود. این کار قابل بازگشت نیست، حتی به‌صورت رکورد باطل‌شده. ادامه می‌دهید؟',
      'rebuy_not_eligible_note': 'بر اساس قوانین فعلی میز، این بازیکن در این سطح مجاز به شارژ مجدد نیست.',
      'money_in_buyin_rebuy': 'ورودی پول (خرید ورود + شارژ مجدد)',
      'money_out_cashout_rake': 'خروجی پول (تسویه + راک + انعام دیلر)',
      'money_out_cashout_rake_tips': 'خروجی پول (تسویه + راک + انعام دیلر)',
      'cash_drops': 'انتقال به گاوصندوق',
      'export_failed': 'خروجی گرفتن ناموفق بود',
      'backup_failed': 'پشتیبان‌گیری ناموفق بود',
      'restore_failed': 'بازیابی ناموفق بود',
      'money_moving_with': 'پول همراه بازیکن',
      'move_player_title': 'جابجایی',
      'transfer_amount_label': 'مبلغی که از این میز برداشته می‌شود',
      'transfer_amount_helper': 'ژتون‌هایی را که بازیکن با خود می‌برد بشمارید.',
      'transfer_table_note': 'این مبلغ از میز مبدأ کم و به میز مقصد اضافه می‌شود. جمع کل جلسه تغییری نمی‌کند — پول فقط میزش عوض شده است.',
      'move_player_note': 'از شما پرسیده می‌شود چه مبلغی همراه بازیکن منتقل می‌شود. خرید ورود، شارژ مجدد و تسویه‌های قبلی او هرگز بازنویسی نمی‌شوند.',
      // Month names (Reports)
      'lifetime_label': 'مجموع کل',
      'month_1': 'ژانویه',
      'month_2': 'فوریه',
      'month_3': 'مارس',
      'month_4': 'آوریل',
      'month_5': 'مه',
      'month_6': 'ژوئن',
      'month_7': 'ژوئیه',
      'month_8': 'اوت',
      'month_9': 'سپتامبر',
      'month_10': 'اکتبر',
      'month_11': 'نوامبر',
      'month_12': 'دسامبر',
      // Chip sound samples (Settings)
      'sound_chip_1_title': 'تک ژتون',
      'sound_chip_1_desc': 'صدای گذاشتن یک ژتون',
      'sound_chip_2_title': 'ریختن ژتون',
      'sound_chip_2_desc': 'ریختن یک مشت ژتون',
      'sound_chip_3_title': 'ریختن ژتون ۲',
      'sound_chip_3_desc': 'یک مشت واضح‌تر با طنین روشن‌تر',
      'sound_chip_4_title': 'آبشار ژتون',
      'sound_chip_4_desc': 'ریزش کوتاه‌تر، نشستن ژتون‌ها',
      'sound_chip_5_title': 'ریزش ژتون',
      'sound_chip_5_desc': 'آبشاری بلند روی میز',
      'sound_chip_6_title': 'ریزش ژتون ۲',
      'sound_chip_6_desc': 'کامل‌ترین ریزش با بلندترین طنین',
      // --- Player classification & access status ---
      'tag_short_vip': 'وی‌آی‌پی',
      'tag_short_regular': 'عادی',
      'tag_short_problem': 'پرخطر',
      'tag_short_tilt': 'تیلت',
      'player_type': 'نوع بازیکن',
      'change_player_type': 'تغییر نوع بازیکن',
      'manage_player': 'مدیریت بازیکن',
      'player_type_classification_note': 'فقط دسته‌بندی. جلسات، تراکنش‌ها و آمار کلی در اینجا تغییر نمی‌کنند.',
      'blacklist': 'لیست سیاه',
      'unblacklist': 'خروج از لیست سیاه',
      'blacklisted': 'در لیست سیاه',
      'blacklisted_caps': 'در لیست سیاه',
      'blacklisted_player': 'بازیکن در لیست سیاه',
      'blacklist_player_q': 'بازیکن به لیست سیاه افزوده شود؟',
      'blacklist_warning_body': 'علامت‌گذاری می‌شود و پیش از نشاندن او در هر جلسه یا میز آینده به شما هشدار داده خواهد شد.',
      'blacklist_warning_history': 'سوابق، آمار و جلسات گذشته او تغییری نمی‌کند.',
      'is_currently_blacklisted': 'هم‌اکنون در لیست سیاه است.',
      'blacklist_seat_anyway': 'در صورت تمایل همچنان می‌توانید او را سر میز بنشانید.',
      'continue_action': 'ادامه',
      'filter_all': 'همه',
      'sort_recent': 'اخیر',
      'sort_name': 'نام',
      'sort_sessions': 'جلسات',
      'sort_profit': 'سود',
      // --- Dealer tips ---
      'dealer_tips': 'انعام دیلر',
      'total_dealer_tips': 'مجموع انعام دیلر',
      // --- Table-to-table transfer legs ---
      'transfer_out': 'انتقال خروجی',
      'transfer_in': 'انتقال ورودی',
      'chips_to_player': 'ژتون به',
      'chips_from_player': 'ژتون از',
      // --- Timeline type summary ---
      'total_prefix': 'مجموع',
      // --- Home ---
      'total_rake_label': 'مجموع راک',
      'signature_multi_stroke_hint': 'با هر تعداد حرکت قلم که لازم است امضا کنید — برداشتن قلم امضا را پایان نمی‌دهد. پس از اتمام، تایید را بزنید.',
      'confirm_signature': 'تایید امضا',
      'redraw': 'رسم دوباره',
      'sample_signature': 'نمونه امضا',
      'verify_signature': 'بررسی امضا',
      'sample_on_file': 'نمونه ثبت‌شده',
      'transaction_signature': 'امضای این تراکنش',
      'no_sample_signature': 'برای این بازیکن نمونه امضایی ثبت نشده است.',
      'zoom': 'بزرگ‌نمایی',
      'reset_zoom': 'بازنشانی بزرگ‌نمایی',
      'pinch_to_zoom': 'برای بزرگ‌نمایی دو بار ضربه بزنید یا انگشتان را باز کنید',
      'transaction_type': 'نوع تراکنش',
      'date': 'تاریخ',
      'saved': 'ذخیره شد',
      'host_signature': 'امضای میزبان',
      'signature_unavailable': 'امضا قابل نمایش نیست',
      'player_sample_signature': 'نمونه امضای بازیکن',
      'sample_signature_hint': 'از بازیکن بخواهید یک بار اینجا امضا کند. فقط برای مقایسه در صورت اختلاف نگهداری می‌شود.',
      'recapture': 'ثبت دوباره',
      'private_tags': 'برچسب‌های خصوصی (فقط بانکر — هرگز به بازیکن نشان داده نمی‌شود)',
      'choose_seat_first': 'ابتدا یک صندلی انتخاب کنید.',
      'no_players_yet': 'هنوز بازیکنی اضافه نشده.',
      'choose_player': 'یک بازیکن انتخاب کنید',
      'quick_actions': 'عملیات سریع',
      'recent_activity': 'فعالیت اخیر',
      'no_transactions_yet': 'هنوز تراکنشی ثبت نشده.',
      'no_transactions_match': 'تراکنشی مطابق فیلتر پیدا نشد.',
      'add_player_first': 'ابتدا یک بازیکن اضافه کنید تا بتوانید خرید ورود، شارژ مجدد یا تسویه ثبت کنید.',
      'one_tap': 'یک ضربه:',
      'or_custom_amount': 'یا مبلغ دلخواه:',
      'pot_size': 'اندازه پات',
      'rake_amount': 'مبلغ راک',
      'confirm_custom_amount': 'تایید مبلغ دلخواه',
      'quick_rake_buttons': 'دکمه‌های راک سریع',
      'enter_valid_amount': 'یک مبلغ معتبر وارد کنید.',
      'signature_required': 'برای تایید، امضای میزبان لازم است.',
      'unusually_large': 'مبلغ غیرعادی بزرگ',
      'let_me_fix_it': 'اصلاح می‌کنم',
      'its_correct': 'درست است',
      'zero_cashout_valid': '۰ معتبر است — وقتی بازیکن تمام ژتون‌هایش را باخته از آن استفاده کنید.',
      'house_rule_notice': 'اعلان قانون خانه',
      'proceed_anyway': 'به هر حال ادامه بده',
      'view_rule': 'مشاهده قانون',
      'full_details': 'جزئیات کامل',
      'player_history': 'تاریخچه بازیکن در همه نشست‌ها',
      'lifetime': 'کل دوران',
      'lifetime_pl': 'سود / زیان کل دوران',
      'no_player_sessions': 'هنوز نشستی برای این بازیکن ثبت نشده.',
      'recent_sessions': 'نشست‌های اخیر',
      'sessions_played': 'نشست بازی‌شده',
      'in_play': 'در بازی',
      'settled': 'تسویه‌شده',
      'playing': 'در حال بازی',
      'move_to_table': 'انتقال به میز دیگر',
      'add_table': 'افزودن میز',
      'rename_table': 'تغییر نام میز',
      'table_name': 'نام میز',
      'table_size': 'اندازه میز',
      'move_dealer': 'جابه‌جایی دکمه دیلر',
      'tap_seat_hint': 'برای افزودن بازیکن روی صندلی خالی بزنید · برای عملیات روی صندلی پر بزنید',
      'more': 'بیشتر',
      'undo_last': 'واگرد آخرین تراکنش',
      'language': 'زبان',
      'default_currency': 'واحد پول پیش‌فرض',
      'table_sounds': 'صداهای میز',
      'chip_sound': 'صدای ژتون پوکر',
      'preview_chip_sound': 'پیش‌نمایش صدای ژتون',
      'chip_sound_desc': 'هنگام ثبت خرید ورود، شارژ مجدد، تسویه، راک یا نشاندن بازیکن صدای ژتون پخش می‌شود.',
      'privacy': 'حریم خصوصی',
      'privacy_mode': 'حالت حریم خصوصی',
      'privacy_desc': 'تمام مبالغ روی صفحه را پنهان می‌کند تا کسی از روی شانه شما اعداد را نبیند. جمع‌ها، بررسی تراز و گزارش‌های خروجی تغییری نمی‌کنند.',
      'show_amounts': 'نمایش مبالغ',
      'hide_amounts': 'پنهان کردن مبالغ (حالت حریم خصوصی)',
      'set_pin': 'تنظیم رمز برنامه',
      'change_pin': 'تغییر رمز برنامه',
      'pin_protect': 'هنگام باز شدن از برنامه محافظت می‌کند',
      'enter_pin': 'رمز را وارد کنید',
      'enter_pin_confirm': 'برای تایید رمز را وارد کنید',
      'unlock': 'باز کردن',
      'pin_digits': 'رمز ۴ تا ۶ رقمی',
      'backup_all': 'پشتیبان‌گیری از همه داده‌ها',
      'backup_desc': 'همه نشست‌ها، بازیکنان، تراکنش‌ها، میزها و تنظیمات را در یک فایل JSON ذخیره می‌کند',
      'restore_backup': 'بازیابی از پشتیبان',
      'restore_desc': 'یک فایل JSON که قبلاً خروجی گرفته‌اید انتخاب کنید',
      'backup_created': 'پشتیبان ساخته شد و آماده اشتراک‌گذاری است.',
      'session_report': 'گزارش نشست',
      'possible_causes': 'دلایل احتمالی:',
      'all_reconcile': 'تمام خریدها، شارژها، تسویه‌ها و راک کاملاً تراز است.',
      'session_ended_readonly': 'نشست پایان یافت — فقط خواندنی',
      'confirm_close_session': 'تایید و بستن نشست',
      'go_back_fix': 'بازگشت و اصلاح',
      'next_level': 'سطح بعدی',
      'view_full_timeline': 'مشاهده کامل خط زمانی ←',
      'show_voided': 'نمایش باطل‌شده‌ها',
      'voided': 'باطل شد',
      'edited': 'ویرایش شد',
      'delete_permanently': 'حذف دائمی',
      'transaction_updated': 'تراکنش به‌روزرسانی شد.',
      'filter_by_player': 'فیلتر بر اساس بازیکن',
      'all_players': 'همه بازیکنان',
      'session_timer': 'تایمر نشست',
      'session_duration': 'مدت نشست',
      'time_remaining': 'زمان باقی‌مانده',
      'minutes': 'دقیقه',
      'no_limit': 'بدون محدودیت',
      'ten_min_remaining': '۱۰ دقیقه باقی مانده',
      'session_finished': 'نشست به پایان رسید',
      'start_timer': 'شروع تایمر',
      'stop_timer': 'توقف تایمر',
      'complete_ledger': 'دفتر کامل',
      'every_action': 'تمام عملیات این بازیکن به ترتیب زمانی',
      'tournament': 'تورنمنت',
      'cash_game': 'بازی نقدی',
      'game_mode': 'حالت بازی',
      'tournament_setup': 'تنظیمات تورنمنت',
      'tournament_setup_hint': 'هزینه ورود، سهم خانه و ساختار اولیه بلایندها. پس از شروع، هر سطح قابل تنظیم است.',
      'tournament_buy_in': 'ورودی تورنمنت',
      'house_fee_per_entry': 'سهم خانه از هر ورودی',
      'rebuy_cost': 'هزینه شارژ مجدد',
      'blank_for_none': 'برای نداشتن خالی بگذارید',
      'starting_stack': 'چیپ اولیه',
      'level_length': 'مدت سطح (دقیقه)',
      'blind_structure': 'ساختار بلایندها',
      'blind_structure_hint': 'برای جابه‌جایی بکشید، برای ویرایش ضربه بزنید. هر تعداد سطح و استراحت می‌توانید اضافه کنید.',
      'structure_saved': 'ساختار بلایندها ذخیره شد.',
      'add_level': 'افزودن سطح',
      'add_break': 'افزودن استراحت',
      'level': 'سطح',
      'is_break': 'این یک استراحت است',
      'ante': 'آنته',
      'duration_minutes': 'مدت (دقیقه)',
      'prize_pool': 'استخر جایزه',
      'payouts': 'جوایز',
      'entries': 'ورودی‌ها',
      'house_fee': 'سهم خانه',
      'unpaid': 'پرداخت‌نشده',
      'rankings': 'رتبه‌بندی',
      'still_in': 'در بازی',
      'eliminated': 'حذف‌شده',
      'eliminate': 'حذف',
      'eliminate_hint': 'رتبه از روی تعداد بازیکنان باقی‌مانده محاسبه می‌شود، پس بازیکنان را به ترتیب حذف کنید.',
      'finishes_in_the_money': 'با جایزه به پایان می‌رسد:',
      'finishes_outside_money': 'بدون جایزه به پایان می‌رسد.',
      'next': 'بعدی',
      'previous_level': 'سطح قبلی',
      'reset': 'بازنشانی',
      'five_min_remaining': '۵ دقیقه باقی مانده',
      'one_min_remaining': '۱ دقیقه باقی مانده',
      'level_finished': 'سطح تمام شد — بلایندها بالا رفت',
      'total': 'مجموع',
      'add_place': 'افزودن رتبه',
      'suggest': 'پیشنهاد',
      'payouts_must_total_100': 'درصد جوایز باید دقیقاً ۱۰۰٪ شود.',
      'session_summary': 'خلاصه نشست',
      'player_performance': 'عملکرد بازیکنان',
      'lifetime_statistics': 'آمار کل دوران',
      'monthly_statistics': 'آمار ماهانه',
      'banker_profit': 'سود بانکر',
      'export': 'خروجی',
      'share': 'اشتراک‌گذاری',
      'generated': 'تولید شده',
      'no_data_yet': 'هنوز داده‌ای نیست.',
      'profit_loss': 'سود / زیان',
      'net': 'خالص',
      'months': 'ماه',
      'average': 'میانگین',
      'more_in_export': 'مورد دیگر در فایل خروجی',
      'tournament_report': 'گزارش تورنمنت',
      'app_start_failed': 'دفتر پوکر اجرا نشد',
      'verified_session_level': 'فقط در سطح نشست بررسی می‌شود — مجموع خریدها و شارژها در برابر مجموع تسویه‌ها و راک.',
      'timer_hint': 'وقتی ۱۰ دقیقه باقی بماند و وقتی زمان تمام شود به شما اطلاع داده می‌شود. نشست هرگز خودکار پایان نمی‌یابد.',
      'tables_upper': 'میزها',
      'per_table_note': 'ارقام هر میز، پول در جریان همان میز است. بررسی تراز بالا کل نشست را پوشش می‌دهد.',
      'zero_valid_bustout': 'برای تسویه بازیکن حذف‌شده، ۰ معتبر است.',
      'resign_to_confirm': 'برای تایید این ویرایش دوباره امضا کنید:',
      'signature_required_edit': 'برای تایید این ویرایش امضا لازم است.',
      'search_by_player_or_note': 'جستجو بر اساس بازیکن یا یادداشت',
      'house_rules_updated': 'قوانین خانه به‌روزرسانی شد.',
      'open_session_for_rules': 'برای مشاهده یا ویرایش قوانین، یک نشست فعال باز کنید.',
      'enforce_rebuy_levels': 'اعمال محدودیت سطح شارژ مجدد',
      'rebuy_unlock_note': 'هر دو سطح، یک شارژ مجدد اضافه آزاد می‌شود.',
      'five_slots_note': 'پنج جایگاه که خودتان تعیین می‌کنید — مبالغ یک‌ضربه‌ای در جمع‌آوری راک.',
      'save_house_rules': 'ذخیره قوانین خانه',
      'under': 'زیر',
      'tier_default_note': 'با جدول پلکانی پیش‌فرض شروع می‌شود؛ پس از باز شدن نشست از قوانین خانه دقیق‌تر تنظیم کنید.',
      'define_five_note': 'پنج مبلغ راک یک‌ضربه‌ای امشب را تعیین کنید. هر زمان از قوانین خانه قابل تغییر است.',
      'host_signature_required_tx': 'برای تایید این تراکنش امضای میزبان لازم است.',
      'sample_signature_on_file': 'نمونه امضای ثبت‌شده',
      'actual_payout_note': 'مبلغ واقعی پرداختی را وارد کنید — محدود به مبلغ خرید بازیکن نیست.',
      'mixed_currency_note': 'این بازیکن نشست‌هایی با چند واحد پول دارد، بنابراین جمع کل نمایش داده نمی‌شود. نتایج هر نشست دقیق است.',
      'ask_player_sign_note': 'از بازیکن بخواهید یک بار اینجا امضا کند. فقط برای مقایسه در صورت اختلاف نگهداری می‌شود.',
      'activation_title': 'فعال‌سازی پوکر لجر',
      'activation_subtitle': 'این نسخه برای استفاده به کلید لایسنس نیاز دارد.',
      'license_key': 'کلید لایسنس',
      'license_key_hint': 'کلید لایسنسی که دریافت کرده‌اید را وارد کنید',
      'activate': 'فعال‌سازی',
      'activation_success': 'فعال شد. سپاسگزاریم.',
      'activation_how_title': 'چگونه لایسنس دریافت کنیم',
      'activation_how_body': 'شناسه دستگاه زیر را برای مالک پوکر لجر ارسال کنید تا کلید لایسنس این دستگاه صادر شود.',
      'device_id': 'شناسه دستگاه',
      'platform': 'پلتفرم',
      'customer_id': 'شناسه مشتری',
      'device_id_copied': 'شناسه دستگاه کپی شد',
      'copy': 'کپی',
      'app_lock': 'قفل برنامه',
      'app_lock_title': 'پوکر لجر قفل است',
      'app_lock_reason': 'برای باز کردن دفتر خود هویتتان را تأیید کنید.',
      'app_lock_unlock': 'باز کردن قفل',
      'app_lock_enable': 'فعال کردن قفل برنامه',
      'app_lock_enabled': 'قفل برنامه فعال است',
      'app_lock_disabled': 'قفل برنامه غیرفعال است',
      'app_lock_desc': 'هر بار که پوکر لجر را باز می‌کنید، اثر انگشت، چهره یا رمز دستگاه شما را می‌خواهد — همان حفاظتی که برنامه‌های بانکی دارند.',
      'app_lock_status': 'وضعیت',
      'auto_lock': 'قفل خودکار',
      'auto_lock_desc': 'پوکر لجر چه مدت می‌تواند در پس‌زمینه بماند تا دوباره قفل شود.',
      'lock_immediately': 'بلافاصله',
      'lock_after_1': 'پس از ۱ دقیقه',
      'lock_after_5': 'پس از ۵ دقیقه',
      'lock_after_15': 'پس از ۱۵ دقیقه',
      'app_lock_failed': 'شناسایی نشد. دوباره تلاش کنید.',
      'app_lock_cancelled': 'تأیید هویت لغو شد. پوکر لجر قفل می‌ماند.',
      'app_lock_not_recognized': 'شناسایی نشد',
      'app_lock_required': 'تأیید هویت لازم است',
      'app_lock_not_enrolled': 'روی این دستگاه اثر انگشت، چهره یا قفل صفحه تنظیم نشده است. برای استفاده از قفل برنامه، در تنظیمات دستگاه یکی را اضافه کنید.',
      'app_lock_unavailable': 'این دستگاه از قفل برنامه پشتیبانی نمی‌کند.',
      'app_lock_locked_out': 'تلاش‌های بیش از حد. دستگاه شما تأیید هویت را موقتاً مسدود کرده است — از رمز دستگاه استفاده کنید یا کمی بعد تلاش کنید.',
      'app_lock_privacy_note': 'دستگاه شما اثر انگشت، چهره یا رمز را بررسی می‌کند. پوکر لجر هرگز آن‌ها را نمی‌بیند و ذخیره نمی‌کند.',
      'app_lock_biometrics_available': 'زیست‌سنجی روی این دستگاه در دسترس است',
      'app_lock_credential_only': 'فقط رمز، الگو یا گذرواژه دستگاه',
      'app_lock_unsupported_note': 'روی این دستگاه قفل صفحه یا زیست‌سنجی تنظیم نشده، بنابراین قفل برنامه فعال نمی‌شود.',
      'chip_bank': 'بانک ژتون',
      'chip_bank_desc': 'ژتون‌های فیزیکی خود را مدیریت کنید — تعداد هر ارزش و ارزش کل مجموعه.',
      'chip_inventory': 'موجودی ژتون',
      'add_chip_type': 'افزودن نوع ژتون',
      'edit_chip_type': 'ویرایش نوع ژتون',
      'chip_name': 'نام ژتون',
      'chip_name_optional': 'نام ژتون (اختیاری)',
      'chip_color': 'رنگ ژتون',
      'chip_color_optional': 'رنگ ژتون (اختیاری)',
      'chip_value': 'ارزش ژتون',
      'chip_value_required': 'ارزش هر ژتون (الزامی)',
      'chip_quantity': 'تعداد',
      'chip_quantity_required': 'تعداد موجود (الزامی)',
      'chip_note_optional': 'یادداشت (اختیاری)',
      'no_color': 'بدون رنگ',
      'total_chip_bank_value': 'ارزش کل بانک ژتون',
      'total_chips': 'کل ژتون‌ها',
      'chip_types': 'انواع ژتون',
      'value_each': 'هر عدد',
      'no_chips_yet': 'هنوز نوع ژتونی اضافه نشده است.',
      'no_chips_hint': 'اولین ارزش ژتون خود را اضافه کنید. فقط ارزش و تعداد الزامی است — نام و رنگ اختیاری هستند.',
      'chip_added': 'نوع ژتون اضافه شد',
      'chip_updated': 'نوع ژتون به‌روزرسانی شد',
      'chip_removed': 'نوع ژتون حذف شد',
      'remove_chip_confirm': 'این نوع ژتون از موجودی حذف شود؟ این کار بر هیچ نشست، بازیکن یا تراکنشی اثر نمی‌گذارد.',
      'chip_value_invalid': 'ارزش ژتون باید بزرگ‌تر از صفر باشد.',
      'chip_quantity_invalid': 'تعداد باید صفر یا بیشتر باشد.',
      'last_updated': 'آخرین به‌روزرسانی',
      'chip_bank_ledger_note': 'این فقط یک موجودی فیزیکی است و هرگز بر خریدها، موجودی بازیکنان یا تسویه نشست‌ها اثر نمی‌گذارد.',
      'update_inventory': 'به‌روزرسانی موجودی',
      'unnamed_chip': 'ژتون بدون نام',
      'chip_tracking': 'ردیابی ژتون',
      'distribute_chips': 'توزیع ژتون',
      'chips_given': 'ژتون‌های داده‌شده',
      'chip_distribution': 'توزیع ژتون',
      'chip_distribution_optional': 'اختیاری — ثبت کنید چه ژتون‌هایی تحویل داده‌اید.',
      'suggest_chips': 'پیشنهاد',
      'clear_chips': 'پاک کردن',
      'chip_total': 'جمع ژتون‌ها',
      'target_amount': 'مبلغ تراکنش',
      'chip_mismatch_title': 'ارزش ژتون مطابقت ندارد',
      'chip_mismatch_body': 'ارزش ژتون‌های انتخابی با مبلغ این تراکنش برابر نیست. این مجاز است و مبلغ در هر صورت ثبت می‌شود، اما لطفاً تأیید کنید که عمدی است.',
      'chip_mismatch_short': 'ژتون‌ها با مبلغ مطابقت ندارند',
      'record_anyway': 'به هر حال ثبت کن',
      'chips_match': 'ژتون‌ها با مبلغ مطابقت دارند',
      'bank_cannot_cover': 'بانک این تعداد ژتون را به‌صورت فیزیکی ندارد.',
      'skip_chips': 'رد کردن ردیابی ژتون',
      'chip_audit': 'حسابرسی ژتون',
      'chip_reconciliation': 'تطبیق ژتون',
      'total_inventory': 'کل موجودی',
      'in_bank': 'در بانک',
      'on_tables': 'روی میزها',
      'with_players': 'نزد بازیکنان',
      'removed_chips': 'خارج‌شده',
      'accounted_for': 'محاسبه‌شده',
      'expected_in_bank': 'مورد انتظار در بانک',
      'counted_in_bank': 'شمارش‌شده',
      'physical_count': 'شمارش فیزیکی',
      'physical_count_hint': 'ژتون‌ها را بشمارید و تعداد واقعی را وارد کنید. برای رد کردن یک ارزش، خالی بگذارید.',
      'chips_balanced': 'تمام ژتون‌های شمارش‌شده تراز هستند.',
      'chips_discrepancy': 'مغایرت ژتون',
      'chips_missing': 'محاسبه‌نشده',
      'chips_extra': 'بیش از حد انتظار',
      'possible_locations': 'ابتدا این‌ها را بررسی کنید',
      'not_verified_note': 'هنوز شمارش فیزیکی وارد نشده، بنابراین چیزی تأیید نشده است. برای تطبیق، شمارش را وارد کنید.',
      'verify_count': 'وارد کردن شمارش فیزیکی',
      'chip_movements': 'جابه‌جایی ژتون‌ها',
      'movement_history': 'تاریخچه جابه‌جایی',
      'no_movements_yet': 'هنوز جابه‌جایی ژتونی ثبت نشده است.',
      'chips_held': 'ژتون‌های فیزیکی نزد بازیکن',
      'total_chip_value': 'ارزش کل ژتون‌ها',
      'no_chips_held': 'ژتون فیزیکی برای این بازیکن ثبت نشده است.',
      'chips_on_table': 'ژتون‌های این میز',
      'all_tables_chips': 'ژتون‌های همه میزها',
      'move_chips': 'جابه‌جایی ژتون',
      'from_location': 'از',
      'to_location': 'به',
      'location_bank': 'بانک',
      'location_table': 'میز',
      'location_player': 'بازیکن',
      'location_removed': 'خارج‌شده از بازی',
      'reason_buy_in': 'خرید ورود',
      'reason_rebuy': 'شارژ مجدد',
      'reason_add_on': 'افزودنی',
      'reason_cash_out': 'تسویه',
      'reason_table_float': 'موجودی میز',
      'reason_rake': 'راک',
      'reason_adjustment': 'اصلاح',
      'reason_transfer': 'انتقال',
      'chip_tracking_note': 'فقط ردیابی فیزیکی ژتون. هرگز خریدها، موجودی‌ها، راک یا تسویه را تغییر نمی‌دهد.',
      'players_holding_chips_note': 'ژتون‌های نزد بازیکنان گم‌شده نیستند — برد و باخت در طول شب ژتون‌ها را جابه‌جا می‌کند. آن‌ها فقط در محل خود شمرده می‌شوند.',
      'chips_returned': 'بازگشته به بانک',
      'return_chips': 'بازگرداندن ژتون به بانک',
      'movement_recorded': 'جابه‌جایی ژتون ثبت شد',
      'set_duration': 'مدت تایمر',
      'table_duration_desc': 'فقط برای این میز. میزهای دیگر تایمر مستقل خود را دارند.',
      'no_timer': 'بدون تایمر',
      'custom_minutes': 'دلخواه (دقیقه)',
      'timer_finished': 'پایان یافت',
      'minute_timer_finished': 'دقیقه‌ای به پایان رسید',
      'view_table': 'مشاهده میز',
      'total_rake': 'مجموع راک',
      'bank': 'بانک',
      'bank_only': 'فقط موجودی بانک',
      'cancel_count': 'لغو شمارش',
      'chip_accounting': 'حسابداری ژتون',
      'chip_bank_critical_alert': 'موجودی بانک ژتون بحرانی است — ۳۰٪ یا کمتر از موجودی اولیه باقی مانده است.',
      'chip_bank_low_alert': 'موجودی بانک ژتون رو به اتمام است — نیمی از موجودی اولیه توزیع شده است.',
      'chip_composition_updated': 'ترکیب ژتون‌ها به‌روزرسانی شد',
      'chip_exchange': 'تعویض ژتون',
      'chip_exchange_desc': 'تعویض ارزش ژتون‌ها با بانک به ارزش برابر. هیچ پولی جابه‌جا نمی‌شود.',
      'chips_balanced_body': 'ژتون‌های شمرده‌شده با آنچه دفتر حرکات انتظار دارد مطابقت دارد. همه ژتون‌ها حساب‌شده‌اند.',
      'chips_given_to_bank': 'ژتون‌های تحویل‌شده به بانک',
      'chips_held_by_players': 'ژتون‌های نزد بازیکنان',
      'chips_missing_body': 'ژتون‌های شمرده‌شده کمتر از انتظار سوابق است. احتمالاً حرکتی ثبت نشده است. این مورد فقط گزارش می‌شود و اصلاح نمی‌گردد.',
      'chips_on_tables': 'ژتون‌های روی میزها',
      'chips_received_from_bank': 'ژتون‌های دریافتی از بانک',
      'chips_surplus': 'ژتون بیشتر از انتظار',
      'chips_surplus_body': 'ژتون‌های شمرده‌شده بیشتر از انتظار سوابق است. حرکتِ دوباره ثبت‌شده یا ژتون بازگشتیِ ثبت‌نشده را بررسی کنید.',
      'chips_to_transfer': 'ژتون‌های قابل انتقال',
      'choose_both_players': 'هر دو بازیکن را انتخاب کنید.',
      'choose_player_first': 'ابتدا یک بازیکن انتخاب کنید.',
      'choose_source_player_first': 'ابتدا بازیکن مبدأ را انتخاب کنید.',
      'confirm_exchange': 'تأیید تعویض',
      'confirm_transfer': 'تأیید انتقال',
      'counted': 'شمرده‌شده',
      'current_bank_chip_value': 'ارزش فعلی ژتون بانک',
      'difference': 'اختلاف',
      'edit_chip_composition': 'ویرایش ترکیب ژتون',
      'edit_chip_composition_note': 'ژتون‌های فیزیکی تحویل‌شده را اصلاح می‌کند. مبلغ تراکنش تغییر نمی‌کند.',
      'edit_keeps_audit_trail': 'ثبت اصلی حفظ می‌شود. یک برگشت و اصلاحیه افزوده می‌شود تا کل تاریخچه قابل مشاهده بماند.',
      'enter_count': 'ثبت شمارش',
      'exchange_balanced': 'هر دو طرف برابرند',
      'exchange_empty': 'ژتون‌های هر دو طرف را انتخاب کنید.',
      'exchange_must_balance': 'ارزش هر دو طرف باید دقیقاً برابر باشد.',
      'exchange_no_money_note': 'فقط ژتون فیزیکی ثبت می‌شود. تراکنشی ایجاد نمی‌شود و تسویه بدون تغییر می‌ماند.',
      'exchange_recorded': 'تعویض ثبت شد',
      'expected': 'مورد انتظار',
      'expected_total_chips': 'جمع مورد انتظار ژتون‌ها',
      'final_discrepancy': 'اختلاف نهایی',
      'from_player': 'از بازیکن',
      'given': 'تحویل‌شده',
      'included_in_bank_total': 'از قبل در جمع بانک بالا لحاظ شده است',
      'new_chip_total': 'جمع جدید ژتون‌ها',
      'no_chips_recorded': 'برای این تراکنش ژتونی ثبت نشده است.',
      'not_entered': 'وارد نشده',
      'not_yet_verified': 'هنوز راستی‌آزمایی نشده',
      'not_yet_verified_body': 'همه ارقام زیر از دفتر حرکات استخراج شده‌اند و به‌طور ذاتی تراز هستند. برای بررسی در برابر واقعیت، ژتون‌ها را بشمارید و نتیجه را وارد کنید.',
      'of_starting_inventory_remains': 'از موجودی اولیه باقی مانده است',
      'originally_recorded': 'ثبت اولیه',
      'player_chip_transfer': 'انتقال بین بازیکنان',
      'player_chip_transfer_desc': 'انتقال ژتون فیزیکی بین دو بازیکن. بانک و تسویه دست‌نخورده می‌مانند.',
      'player_holds': 'موجودی بازیکن',
      'player_lacks_chips': 'این بازیکن به اندازه کافی از این ژتون‌ها ندارد.',
      'prefill_expected': 'پرکردن با مقدار مورد انتظار',
      'prefill_expected_hint': 'هر فیلد را با مقدار مورد انتظار پر می‌کند تا فقط موارد متفاوت را تغییر دهید. هر سطری را که واقعاً شمرده‌اید تنظیم کنید.',
      'rake_returned_to_bank': 'راک بازگشته به بانک',
      'received': 'دریافت‌شده',
      'reconcile_chips_before_closing': 'تطبیق ژتون‌ها پیش از بستن',
      'reconciliation_never_adjusts': 'این گزارش هرگز ژتون ایجاد یا حذف نمی‌کند. اختلاف واقعی همیشه نمایش داده می‌شود و هرگز پنهانی اصلاح نمی‌گردد.',
      'removed_lost_damaged': 'خارج‌شده / گم‌شده / آسیب‌دیده',
      'save_composition': 'ذخیره ترکیب',
      'select_chips_to_transfer': 'ژتون‌های قابل انتقال را انتخاب کنید.',
      'select_player': 'انتخاب بازیکن',
      'session_chip_reconciliation': 'تطبیق ژتون نشست',
      'starting_bank_chip_value': 'ارزش اولیه ژتون بانک',
      'to_player': 'به بازیکن',
      'transaction_amount': 'مبلغ تراکنش',
      'transfer_no_money_note': 'فقط ژتون فیزیکی ثبت می‌شود. موجودی بانک، مانده‌ها و تسویه هیچ‌کدام تغییر نمی‌کنند.',
      'transfer_recorded': 'انتقال ثبت شد',
      'transfer_value': 'ارزش انتقال',
      'unknown_chip': 'ژتون ناشناخته',
      'unverified': 'راستی‌آزمایی‌نشده',
      'view': 'مشاهده',
      'was': 'قبلاً',
      'license': 'لایسنس',
      'license_status': 'وضعیت لایسنس',
      'license_id': 'شناسه لایسنس',
      'licensed_to': 'صادرشده برای',
      'license_type': 'نوع لایسنس',
      'activation_date': 'تاریخ فعال‌سازی',
      'expiry_date': 'تاریخ انقضا',
      'never_expires': 'بدون انقضا',
      'device_limit': 'حداکثر دستگاه',
      'device_info': 'اطلاعات دستگاه',
      'status_active': 'فعال',
      'status_not_activated': 'فعال نشده',
      'status_expired': 'منقضی شده',
      'status_invalid': 'نامعتبر',
      'deactivate_device': 'غیرفعال کردن این دستگاه',
      'deactivate_desc': 'این دستگاه آزاد می‌شود تا لایسنس روی گوشی دیگری استفاده شود. نشست‌ها، بازیکنان و تراکنش‌های شما حذف نمی‌شوند.',
      'deactivate_confirm': 'این دستگاه غیرفعال شود؟ برای ادامه استفاده دوباره به کلید لایسنس نیاز دارید. هیچ داده‌ای حذف نمی‌شود.',
      'deactivate_done': 'دستگاه غیرفعال شد',
      'license_scope': 'دامنه',
      'owner_master_license': 'لایسنس اصلی مالک',
      'multi_device_note': 'این لایسنس می‌تواند روی چند دستگاه شخصی شما فعال شود. فعال‌سازی دستگاه دیگر، این دستگاه را غیرفعال نمی‌کند.',
      'license_type_club': 'باشگاهی',
      'license_type_full': 'کامل',
      'license_type_standard': 'استاندارد',
      'license_type_trial': 'آزمایشی',
      'license_type_owner': 'مالک',
      'days_remaining': 'روز باقی‌مانده',
      'err_license_empty': 'کلید لایسنس را وارد کنید.',
      'err_license_malformed': 'این متن شبیه کلید لایسنس پوکر لجر نیست. مطمئن شوید همه آن را کپی کرده‌اید.',
      'err_license_signature': 'این کلید لایسنس معتبر نیست. توسط پوکر لجر صادر نشده یا تغییر داده شده است.',
      'err_license_expired': 'این لایسنس منقضی شده است. برای تمدید با مالک تماس بگیرید.',
      'err_license_device': 'این لایسنس به دستگاه دیگری تعلق دارد. از مالک برای این دستگاه کلید بگیرید.',
      'err_license_limit': 'این لایسنس به حداکثر تعداد دستگاه رسیده است.',
      'err_license_future': 'این لایسنس به نسخه جدیدتری از برنامه نیاز دارد.',
      'err_license_tampered': 'فعال‌سازی ذخیره‌شده دیگر معتبر نیست. لطفاً دوباره فعال‌سازی کنید.',
      'license_data_safe_note': 'فعال‌سازی فقط برنامه را باز می‌کند و هرگز به نشست‌ها، بازیکنان یا تراکنش‌های شما دست نمی‌زند.',
      'license_offline_note': 'پس از فعال‌سازی کاملاً آفلاین کار می‌کند و به اینترنت نیاز ندارد.',
      'reactivate': 'فعال‌سازی مجدد',
      'restore_backup_title': 'بازیابی پشتیبان',
      'restore_merge_note': 'این کار پشتیبان انتخاب‌شده را با داده‌های فعلی ادغام می‌کند. نشست‌ها، بازیکنان و تراکنش‌هایی که شناسه یکسان دارند بازنویسی می‌شوند و بقیه داده‌ها حفظ می‌شود. این کار قابل بازگشت نیست.',
      'chip_sound_desc_long': 'هنگام ثبت خرید ورود، شارژ مجدد، تسویه، راک یا نشاندن بازیکن صدای ژتون پخش می‌شود تا بدون نگاه کردن به صفحه متوجه شوید.',
      'privacy_desc_long': 'تمام مبالغ روی صفحه را پنهان می‌کند. جمع‌ها، بررسی تراز و گزارش‌های خروجی تغییر نمی‌کنند.',
      'backup_exports_note': 'همه نشست‌ها، بازیکنان، هویت‌ها، تراکنش‌ها، میزها، تنظیمات و فهرست بازیکنان را در یک فایل JSON ذخیره می‌کند',
      'no_quick_rake_set': 'دکمه راک سریع تنظیم نشده — پنج مبلغ خود را در قوانین خانه تعیین کنید.',
      'heads_up_no_cashout': 'توجه: تسویه‌ای ثبت نشده برای',
      'no_cashout_double_check': 'جمع‌ها همچنان تراز است، اما مطمئن شوید این بازیکنان واقعاً تسویه شده‌اند.',
      'signature_score_disclaimer': 'این امتیاز فقط یک کمک است، نه حکم قطعی. هیچ تراکنشی به‌صورت خودکار مسدود یا تأیید نمی‌شود — تصمیم نهایی با شماست.',
      'edit_player_tooltip': 'ویرایش بازیکن',
      'leave_blank_hide': 'برای پنهان کردن این دکمه خالی بگذارید',
      'five_buttons_note': 'این پنج دکمه بالای جمع‌آوری راک نمایش داده می‌شوند. مبلغ دلخواه همیشه در دسترس است.',
      'no_quick_rake_configured': 'دکمه راک سریع تنظیم نشده — فقط مبلغ دلخواه پرسیده می‌شود.',
      'comparison_note': 'مقایسه بر عهده انسان است — برنامه هرگز امضاها را امتیازدهی نمی‌کند. عدم تطابق دلیل پرسیدن است، نه اثبات.',
      'tables_seating_note': 'میزها فقط چیدمان صندلی‌ها را سازمان می‌دهند. تمام محاسبات مالی در سطح کل نشست باقی می‌ماند.',
      'eg_table_2': 'مثلاً میز ۲',
      'only_one_table_note': 'فقط یک میز در این نشست وجود دارد. از منوی بیشتر میز دیگری اضافه کنید.',
      'view_signature': 'مشاهده امضا',
      'all_tables': 'همه میزها',
      'paused': 'متوقف',
      'closed': 'بسته',
      'pause': 'توقف',
      'reopen': 'بازگشایی',
      'close_table': 'بستن میز',
      'close_table_confirm': 'بستن',
      'close_table_note': 'نشست باز می‌ماند. میزهای دیگر ادامه می‌دهند و می‌توانید این میز را دوباره باز کنید.',
      'table_closed_hint': 'این میز بسته است. برای نشاندن بازیکن یا ثبت مبلغ، آن را باز کنید.',
      'quick_rake': 'راک سریع',
      'rake_from_this_player': 'راک از پات این بازیکن',
      'rake_from_player': 'راک از',
      'rake_general_note': 'راک عمومی نشست — به بازیکن خاصی تعلق ندارد.',
      'rake_from_their_pots': 'راک از پات‌های او',
      'rake_not_in_pl': 'راک درآمد خانه است و هرگز از سود یا زیان بازیکن کم نمی‌شود.',
      'across_all_sessions': 'در همه نشست‌ها',
      'win_rate': 'نرخ برد',
      'average_buy_in': 'میانگین خرید ورود',
      'start_timer_table': 'شروع تایمر میز',
      'chip_sound_pick_hint': 'همه عملیات ژتون از صدایی که اینجا انتخاب می‌کنید استفاده می‌کنند. برای شنیدن روی هر گزینه بزنید.',
      // --- Player identity (Step 1 — no money) ---
      'identity_same_person_title': 'همان شخص است؟',
      'identity_same_person_body': 'کسی با نام {name} از قبل ثبت شده است. برای پیوند این صندلی روی همان شخص بزنید — یا بگویید فرد دیگری است. نام به‌تنهایی کافی نیست.',
      'identity_different_person': 'فرد دیگر',
      'identity_confirm_hint': 'پیوند هرگز خودکار نیست. اگر مطمئن نیستید «فرد دیگر» را انتخاب کنید — دو نفر می‌توانند هم‌نام باشند.',
      'identity_last_seen': 'آخرین حضور',
      'identity_no_previous_seat': 'صندلی قبلی پیوند نشده',
      'identity_restore_conflict_title': 'تداخل هویت',
      'identity_restore_conflict_same_id': 'این هویت پشتیبان همان شناسه را دارد اما نام‌ها یکی نیستند. بازنویسی نام آن شخص را عوض می‌کند. کدام املا بماند؟',
      'identity_restore_conflict_same_name': 'این هویت پشتیبان همان نام را دارد اما شناسه متفاوت است. ادغام نمی‌شوند. اگر دو نفر هستند هر دو را نگه دارید، یا مورد ورودی را رد کنید.',
      'identity_keep_local': 'مال خودم بماند',
      'identity_take_backup': 'از پشتیبان',
      'identity_keep_both': 'هر دو بمانند',
      'identity_conflicts_resolved': 'تداخل‌های هویت یکی‌یکی حل شدند.',
      'identity_conflicts_pending': 'برخی هویت‌ها وارد نشدند چون با افراد همین دستگاه تداخل دارند.',
      // --- Financial Ledger (Step 2 — read-only account) ---
      'player_account': 'حساب بازیکن',
      'view_financial_account': 'حساب مالی',
      'outstanding_balance': 'مانده بدهی',
      'not_recorded': 'ثبت نشده',
      'not_recorded_hint': 'برای این شخص در این واحد پول هیچ رویداد مالی ثبت نشده است. این با تسویه‌شده بودن فرق دارد — یعنی دفتر مالی هنوز سابقه‌ای ندارد.',
      'not_recorded_no_identity': 'این صندلی به هویت دائمی پیوند نشده، بنابراین حساب مالی برای نمایش وجود ندارد.',
      'financial_history': 'تاریخچه مالی',
      'no_financial_events': 'هنوز رویداد مالی ثبت نشده است.',
      'fin_cash_in_for_chips': 'دریافت نقد در برابر ژتون',
      'fin_cash_out_for_chips': 'پرداخت نقد در برابر ژتون',
      'fin_credit_issued': 'اعتبار داده‌شده',
      'fin_credit_repaid': 'بازپرداخت اعتبار',
      'fin_cash_out_unbacked': 'تسویه بدون پشتوانه',
      'fin_front_money_in': 'ورود ودیعه',
      'fin_front_money_out': 'خروج ودیعه',
      'fin_deposit_in': 'ورود ودیعه',
      'fin_deposit_out': 'خروج ودیعه',
      'fin_adjustment': 'اصلاحیه',
      'fin_reversal_of': 'برگشت',
      'payment_cash': 'نقد',
      'payment_bank_transfer': 'حواله بانکی',
      'payment_other': 'سایر',
      'player_owes_banker': 'بازیکن به بانکر بدهکار است',
      'banker_holds_money': 'بانکر پول این بازیکن را نگه داشته است',
      'financial_settled': 'تسویه‌شده — مانده‌ای نیست',
      'backdated': 'تاریخ گذشته',
      'reversed_event': 'برگشت',
      'audit_linked_tx': 'تراکنش ژتون مرتبط (فقط برای پیگیری — اثبات پرداخت نیست)',
      'financial_account_chip_note': 'پول واقعی بین شما و این شخص. خرید ورود، شارژ مجدد و تسویه ژتون دفتر جداگانه‌ای است و اینجا جمع نمی‌شود.',
      // --- Step 3: cash-in / credit / marker capture ---
      'how_was_this_paid': 'هزینه این ژتون‌ها را چطور پرداخت کرد؟',
      'funding_not_inferred': 'خرید ورود ژتون اثبات پرداخت نیست. آنچه واقعاً رخ داد را انتخاب کنید، یا رد کنید تا «ثبت نشده» بماند.',
      'funding_paid_cash': 'نقد پرداخت شد',
      'funding_paid_cash_hint': 'این مبلغ را تحویل داد. کسی به کسی بدهکار نیست.',
      'funding_credit': 'اعتبار',
      'funding_credit_hint': 'ژتون الان، پرداخت بعداً. بدهی ایجاد می‌شود.',
      'funding_marker': 'مارکر',
      'funding_marker_hint': 'همان اعتبار، با امضای بازیکن به‌عنوان سند.',
      'funding_not_recorded': 'رد — ثبت نشود',
      'funding_not_recorded_hint': 'رویداد مالی نوشته نمی‌شود. این با تسویه‌شده بودن فرق دارد.',
      'marker_sign_hint': 'از بازیکن بخواهید این مارکر را امضا کند.',
      'confirm_marker': 'تأیید مارکر',
      'how_was_cashout_paid': 'این تسویه چطور پرداخت شد؟',
      'cashout_funding_hint': 'برگشت ژتون اثبات پرداخت نقد به بازیکن نیست.',
      'cashout_paid_cash': 'نقد پرداخت شد',
      'cashout_paid_cash_hint': 'در برابر ژتون‌های برگشتی این مبلغ را نقد دادید.',
      'cashout_unbacked': 'بدون پشتوانه',
      'cashout_unbacked_hint': 'نقدی دادید که پوشش داده نشده بود. او به شما بدهکار است.',
      'financial_record_failed': 'حرکت ژتون ذخیره شد. ثبت مالی ناموفق بود',
      'record_credit_repaid': 'ثبت بازپرداخت اعتبار',
      'credit_repaid_hint': 'بدهی خود را پرداخت می‌کند. این خرید ورود ژتون نیست.',
      // --- Step 4: Deposit ---
      'accept_front_money': 'پذیرش ودیعه',
      'return_front_money': 'بازگرداندن ودیعه',
      'front_money_in_hint': 'پول نقد را به‌عنوان ودیعه به شما سپرد. این خرید ورود ژتون نیست و بازپرداخت اعتبار هم نیست.',
      'front_money_out_hint': 'ودیعه او را برمی‌گردانید. این تسویه ژتون نیست.',
      'front_money_held': 'ودیعه باقی‌مانده',
      'accept_deposit': 'پذیرش ودیعه',
      'return_deposit': 'بازگرداندن ودیعه',
      'use_deposit_for_chips': 'استفاده از ودیعه برای ژتون',
      'remaining_deposit': 'ودیعه باقی‌مانده',
      'deposit_in_hint': 'پول نقد را به‌عنوان ودیعه به شما سپرد. تا وقتی آن را تبدیل نکنید خرید ورود، اعتبار یا پول بازی نیست.',
      'deposit_out_hint': 'ودیعه نقد را برگردانید. این تسویه ژتون نیست و در تخفیف اثر ندارد.',
      'deposit_use_chips_hint': 'این مبلغ از ودیعه به ژتون تبدیل می‌شود. از ودیعه کم می‌شود و به‌عنوان دریافت نقد در برابر ژتون ثبت می‌گردد. خرید ورود جداگانه استنباط نمی‌شود.',
      'deposit_need_session': 'قبل از تبدیل ودیعه به ژتون، این شخص را در یک نشست زنده بنشانید.',
      'deposit_need_seat': 'این شخص در نشست نشسته نیست. قبل از تبدیل ودیعه او را بنشانید.',
      'deposit_sign_hint': 'میزبان: امضا کنید که این ژتون‌ها از ودیعه اوست.',
      // --- Step 5: Settlement / Reports ---
      'settle_poker_chips': 'تسویه ژتون',
      'settle_financial_account': 'حساب مالی',
      'settle_deposit': 'ودیعه',
      'settle_buy_in': 'خرید ورود',
      'settle_rebuy': 'شارژ مجدد',
      'settle_cash_out': 'تسویه',
      'settle_current_pot': 'پول روی میز / مغایرت',
      'settle_cashed_out': 'تسویه ثبت شده',
      'settle_not_cashed_out': 'تسویه‌ای ثبت نشده',
      'settle_credit_issued': 'اعتبار داده‌شده',
      'settle_credit_repaid': 'بازپرداخت اعتبار',
      'settle_unbacked': 'تسویه بدون پشتوانه',
      'settle_cash_in_for_chips': 'نقد پرداخت‌شده بابت ژتون',
      'settle_cash_out_for_chips': 'نقد دریافت‌شده بابت ژتون برگشتی',
      'settle_deposit_in': 'ودیعه دریافت‌شده',
      'settle_deposit_used': 'ودیعه استفاده‌شده برای ژتون',
      'settle_deposit_returned': 'ودیعه بازگردانده‌شده',
      'settle_deposit_remaining': 'ودیعه باقی‌مانده',
      'settle_warn_deposit': 'در این نشست هنوز ودیعه نزد بانکر است. پس از بستن نشست هم می‌توانید آن را برگردانید.',
      'settle_warn_credit': 'در این نشست هنوز اعتبار تسویه‌نشده وجود دارد. پس از بستن نشست هم می‌توانید بازپرداخت ثبت کنید.',
      'settle_warn_unbacked': 'در این نشست تسویه بدون پشتوانه وجود دارد. پس از بستن نشست هم می‌توانید آن را اصلاح کنید.',
      'void_linked_title': 'رویدادهای مالی مرتبط',
      'void_linked_body': 'این تراکنش ژتون به رویدادهای مالی وصل است. باطل کردن ردیف ژتون آن‌ها را خودکار برنمی‌گرداند. انتخاب کنید چه شود.',
      'void_chip_only': 'فقط تراکنش ژتون باطل شود',
      'void_chip_and_reverse': 'ژتون باطل + رویدادهای مالی مرتبط برگردد',
      'void_chip_only_warn': 'ردیف ژتون باطل شد. رویدادهای مالی مرتبط سر جایشان ماندند و ممکن است اصلاح جداگانه لازم باشد.',
      // --- Step 6: Loss rebate / Discount ---
      'rebate_title': 'تخفیف زیان',
      'rebate_enabled': 'فعال‌سازی تخفیف زیان',
      'rebate_min_loss': 'حداقل زیان نقد واجد شرایط',
      'rebate_percent': 'درصد تخفیف',
      'rebate_hint': 'فقط بازی نقدی. بر اساس پول نقد پرداخت‌شده بابت ژتون است، نه ردیف خرید ورود، اعتبار یا ودیعه.',
      'rebate_granted': 'تخفیف اعطاشده',
      'rebate_returned': 'تخفیف برگشته به خانه',
      'rebate_paid_out': 'تخفیف پرداخت‌شده به بازیکن',
      'rebate_exposed': 'تخفیف هنوز در بازی',
      'rebate_house_retained': 'مانده نزد خانه از پول خود بازیکن',
      'rebate_own_cash_in': 'ورود نقد خود بازیکن',
      'rebate_own_cash_out': 'تسویه ژتون ثبت‌شده',
      'rebate_actual_paid': 'نقد واقعاً پرداخت‌شده به بازیکن',
      'rebate_eligible_loss': 'زیان نقد واجد شرایط',
      'rebate_gross_loss': 'زیان ناخالص نقد خود بازیکن',
      'review_discount': 'بررسی تخفیف',
      'confirm_rebate_grant': 'تأیید اعطای تخفیف',
      'rebate_as_chips': 'اعطا به‌صورت ژتون',
      'rebate_as_cash': 'اعطا به‌صورت نقد',
      'rebate_as_chips_hint': 'ژتون تشویقی. خرید ورود نیست و پول خود بازیکن هم نیست.',
      'rebate_as_cash_hint': 'نقد پرداخت‌شده به بازیکن. خرید ورود ژتون نیست.',
      'rebate_not_eligible': 'تخفیفی برای اعطا نیست',
      'rebate_realize_title': 'تخفیف در این تسویه',
      'rebate_realize_body': 'بازیکن همان مبلغ تسویه را می‌گیرد. تخفیف استفاده‌نشده‌ای که در بازی باخته به خانه برمی‌گردد. تسویه بزرگ‌تر فقط مانده اعطا را برمی‌گرداند — هرگز درصد جدید.',
      'rebate_player_receives': 'بازیکن دریافت می‌کند',
      'rebate_returned_now': 'الان به خانه برگشت',
      'confirm_rebate_realize': 'ثبت تحقق تخفیف',
      'reverse_rebate_grant': 'برگشت این اعطای تخفیف',
      'fin_rebate_granted': 'تخفیف اعطاشده',
      'fin_rebate_recovered': 'تخفیف برگشته به خانه',
      'reason_loss_rebate': 'تخفیف زیان',
      'settle_warn_rebate_chips': 'در این نشست ژتون تخفیف داده شده است. این مبلغ ورودی پول نیست. هنگام تسویه ممکن است دفتر ژتون به همان اندازه کوتاه به نظر برسد.',
      'rebate_form_chips': 'به‌صورت ژتون',
      'rebate_form_cash': 'به‌صورت نقد',
    },
  };

  /// Looks up [key]; falls back to English, then to the key itself.
  String t(String key) => lookup(locale.languageCode, key);

  /// Context-free lookup used by the top-level [tr] helper.
  static String lookup(String languageCode, String key) =>
      _strings[languageCode]?[key] ?? _strings['en']?[key] ?? key;

  bool get isRtl => locale.languageCode == 'fa';
}

/// The locale the app is currently rendering in.
///
/// Kept as a module-level value, set by SettingsProvider whenever the
/// language changes, so [tr] can be called from anywhere — including
/// `static` helpers, bottom-sheet builders and model-adjacent code that
/// have no BuildContext to hand. Localizing the app through a
/// context-only lookup would have meant threading a BuildContext through
/// dozens of static UI helpers, which is exactly the kind of churn that
/// breaks working screens.
String _activeLanguageCode = 'en';

/// Sets the language used by [tr]. Called by SettingsProvider.
void setActiveLanguage(String code) => _activeLanguageCode = code;

String get activeLanguageCode => _activeLanguageCode;

bool get isRtlActive => _activeLanguageCode == 'fa';

/// Translates [key] into the active language.
///
/// Falls back to English, then to the key itself, so a missing
/// translation degrades to readable English rather than a blank label.
String tr(String key) => AppLocalizations.lookup(_activeLanguageCode, key);

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
